---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navidrome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: navidrome-secret
    template:
      data:
        ND_LISTENBRAINZ_API_KEY: "{{ .NAVIDROME_LB_TOKEN }}"
        ND_DBPATH: "postgres://navidrome:{{ .NAVIDROME_DB_PASSWORD }}@postgres-vectorchord-rw.default.svc.cluster.local/navidrome?sslmode=disable"
  data:
    - secretKey: NAVIDROME_LB_TOKEN
      remoteRef:
        key: multi-scrobbler
        property: NAVIDROME_LB_TOKEN
    - secretKey: NAVIDROME_DB_PASSWORD
      remoteRef:
        key: navidrome
        property: NAVIDROME_DB_PASSWORD
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navidrome-pg-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: navidrome-pg-password
    template:
      data:
        username: navidrome
        password: "{{ .NAVIDROME_DB_PASSWORD }}"
  data:
    - secretKey: NAVIDROME_DB_PASSWORD
      remoteRef:
        key: navidrome
        property: NAVIDROME_DB_PASSWORD
