sources:
  - name: Navidrome
    type: subsonic
    data:
      url: http://navidrome.default.svc.cluster.local
      user: "{{ env 'NAVIDROME_USERNAME' }}"
      password: "{{ env 'NAVIDROME_PASSWORD' }}"

clients:
  - name: ListenBrainz
    type: listenbrainz
    data:
      token: "{{ env 'LISTENBRAINZ_TOKEN' }}"
