---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-oidc
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actual-oidc
    template:
      data:
        ACTUAL_OPENID_CLIENT_ID: "{{ .ACTUAL_OIDC_CLIENT_ID }}"
        ACTUAL_OPENID_CLIENT_SECRET: "{{ .ACTUAL_OIDC_CLIENT_SECRET }}"
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: authentik
