# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {}

  required_providers {
    proxmox = { source = "bpg/proxmox", version = "~> 0.97.0" }
    sops    = { source = "carlpett/sops", version = "~> 1.3.0" }
    null    = { source = "hashicorp/null", version = "~> 3.0" }
  }
}

variable "region" {
  type    = string
  default = "home-lab"
}

variable "minio_root_user" {
  type      = string
  sensitive = true
}

variable "minio_root_password" {
  type      = string
  sensitive = true
}

locals {
  ssh_public_key      = file(pathexpand("~/.ssh/id_ed25519.pub"))
  minio_root_user     = var.minio_root_user
  minio_root_password = var.minio_root_password
  minio_barman_ak     = data.sops_file.secrets.data["minio_barman_access_key"]
  minio_barman_sk     = data.sops_file.secrets.data["minio_barman_secret_key"]

  containers = {
    minio01 = {
      vm_id       = 200052
      node_name   = "pve02"
      hostname    = "minio01"
      description = "MinIO LXC on pve02 with Proxmox-managed Ceph volume mountpoint (tenant 200)"
      cpu_cores   = 2
      memory_mb   = 2048
      swap_mb     = 512
      disk_gb     = 16
      bridge      = "vmbr0"
      vlan_id     = 200
      firewall    = false
      features = {
        nesting = true
        keyctl  = true
      }
      ipv4_address    = "10.200.0.52/24"
      ipv4_gateway    = "10.200.0.254"
      ipv6_address    = "fd00:200::52/64"
      ipv6_gateway    = "fd00:200::fffe"
      ssh_public_keys = [local.ssh_public_key]
      tags            = ["storage", "minio", "lxc", "trixie"]
      mount_points = [
        {
          volume = "rbd-vm"
          size   = "200G"
          path   = "/data"
        }
      ]
    }
  }

  minio_provision_commands = [
    "export DEBIAN_FRONTEND=noninteractive",
    "apt-get update -qq >/dev/null",
    "apt-get install -y -qq --no-install-recommends curl ca-certificates >/dev/null",
    "mkdir -p /data/minio /etc/default",
    "curl -fsSL -o /usr/local/bin/minio https://dl.min.io/server/minio/release/linux-amd64/minio",
    "curl -fsSL -o /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc",
    "chmod 755 /usr/local/bin/minio /usr/local/bin/mc",
    "if id -u minio-user >/dev/null 2>&1; then true; elif id -u debian >/dev/null 2>&1; then usermod -l minio-user debian && groupmod -n minio-user debian; else groupadd -g 1000 minio-user && useradd -u 1000 -g 1000 -s /usr/sbin/nologin -M minio-user; fi",
    "usermod -d /nonexistent -s /usr/sbin/nologin minio-user >/dev/null 2>&1 || true",
    "chown -R minio-user:minio-user /data/minio",
    "cat > /etc/default/minio <<'ENV'\nMINIO_VOLUMES=/data/minio\nMINIO_ROOT_USER=${local.minio_root_user}\nMINIO_ROOT_PASSWORD=${local.minio_root_password}\nMINIO_SITE_NAME=homelab-minio\nENV",
    "chmod 600 /etc/default/minio",
    "cat > /etc/systemd/system/minio.service <<'UNIT'\n[Unit]\nDescription=MinIO Object Storage\nDocumentation=https://min.io/docs/minio/linux/index.html\nAfter=network-online.target\nWants=network-online.target\n\n[Service]\nType=notify\nUser=minio-user\nGroup=minio-user\nEnvironmentFile=/etc/default/minio\nExecStart=/usr/local/bin/minio server $MINIO_VOLUMES --console-address :9001\nRestart=on-failure\nRestartSec=5\nTimeoutStartSec=120\nLimitNOFILE=65536\nLimitNPROC=4096\nNoNewPrivileges=yes\n\n[Install]\nWantedBy=multi-user.target\nUNIT",
    "systemctl daemon-reload",
    "systemctl enable --now minio",
    "for i in $(seq 1 12); do curl -fsS -o /dev/null http://localhost:9000/minio/health/ready && break || sleep 5; done",
    "curl -fsS -o /dev/null http://localhost:9000/minio/health/ready",
    "mc alias set local http://localhost:9000 ${local.minio_root_user} ${local.minio_root_password} --quiet",
    "mc mb --ignore-existing local/cnpg-backups",
    "mc admin user add local ${local.minio_barman_ak} ${local.minio_barman_sk} 2>/dev/null || mc admin user enable local ${local.minio_barman_ak}",
    "mc admin policy attach local readwrite --user ${local.minio_barman_ak} 2>/dev/null || true",
  ]
}

module "minio_lxc" {
  source = "../../../modules/proxmox_lxc_role"

  proxmox = {
    datastore_id = "resources"
    vm_datastore = "rbd-vm"
  }

  template = {
    download  = false
    url       = ""
    file_name = ""
    file_id   = "resources:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
  }

  dns_servers = [
    "fd00:0:0:ffff::53",
    "10.255.0.53",
  ]

  containers = local.containers

  provision = {
    enabled            = true
    ssh_user           = "root"
    ssh_private_key    = file(pathexpand("~/.ssh/id_ed25519"))
    ssh_timeout        = "10m"
    wait_for_cloudinit = false
    commands           = local.minio_provision_commands
  }
}

output "minio_lxc_containers" {
  value = module.minio_lxc.containers
}

output "minio_endpoints" {
  value = {
    api     = "http://10.200.0.52:9000"
    console = "http://10.200.0.52:9001"
  }
}
