---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name actions-runner-controller
spec:
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set-controller
  interval: 1h
  timeout: 10m
  maxHistory: 3
  install:
    remediation:
      retries: 5
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
      strategy: rollback
    timeout: 10m
  values:
    fullnameOverride: *name
    replicaCount: 1
    metrics:
      controllerManagerAddr: ":8080"
      listenerAddr: ":8080"
      listenerEndpoint: /metrics
    flags:
      logLevel: info
      updateStrategy: eventual
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 256Mi
