---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: actions-runner-listeners
  labels:
    app.kubernetes.io/name: actions-runner-listeners
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: runner-scale-set-listener
  podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scrapeTimeout: 10s
      metricRelabelings:
        - action: keep
          sourceLabels: [__name__]
          regex: gha_.*
