# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {}

  required_providers {
    cloudflare = { source = "cloudflare/cloudflare", version = "~> 5.0" }
    sops       = { source = "carlpett/sops", version = "~> 1.4.0" }
  }
}

variable "region" {
  type    = string
  default = "home-lab"
}

locals {
  account_id = data.sops_file.secrets.data["cloudflare_account_id"]

  # Must match whatever custom domain task 8c attaches to the deployed
  # Worker (via wrangler, not Terraform -- Terragrunt owns the Access
  # policy, wrangler owns the code push and the Worker's own custom-domain
  # route/DNS record, same GitOps/Terraform split as the rest of this
  # infra). Update this if the actual chosen hostname ends up different.
  hostname = "chief-of-staff-mcp.sulibot.com"
}

# Long-lived (1 year) credential for the MCP client(s) calling this
# Worker -- an AI agent session, not a human browser, so there's no IdP
# login to redirect to. client_id/client_secret are Terraform outputs
# below (client_secret marked sensitive); read them with `terragrunt
# output` after apply and store them yourself -- this Terraform code has
# no capability to write to 1Password, same limit noted throughout
# chief-of-staff's own docs.
resource "cloudflare_zero_trust_access_service_token" "chief_of_staff_mcp" {
  account_id = local.account_id
  name       = "chief-of-staff-mcp"
  duration   = "8760h"

  lifecycle {
    create_before_destroy = true
  }
}

# Plain self_hosted app, same pattern as every other app in the sibling
# cloudflare-access unit -- not the AI Controls MCP portal/gateway
# resource (see file header for why). auto_redirect_to_identity is false
# and no allowed_idps are set: this app is Service-Auth-only, no human
# ever logs into it via browser.
resource "cloudflare_zero_trust_access_application" "chief_of_staff_mcp" {
  account_id                 = local.account_id
  name                       = "chief-of-staff-mcp"
  domain                     = local.hostname
  type                       = "self_hosted"
  session_duration           = "24h"
  auto_redirect_to_identity  = false
  enable_binding_cookie      = false
  http_only_cookie_attribute = false
  options_preflight_bypass   = false

  policies = [{
    name       = "Service token"
    decision   = "non_identity"
    precedence = 1
    include = [{
      service_token = {
        token_id = cloudflare_zero_trust_access_service_token.chief_of_staff_mcp.id
      }
    }]
  }]
}

output "service_token_client_id" {
  value = cloudflare_zero_trust_access_service_token.chief_of_staff_mcp.client_id
}

output "service_token_client_secret" {
  value     = cloudflare_zero_trust_access_service_token.chief_of_staff_mcp.client_secret
  sensitive = true
}

output "access_application_id" {
  value = cloudflare_zero_trust_access_application.chief_of_staff_mcp.id
}
