# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    external = {
      source  = "hashicorp/external"
      version = "~> 2.2"
    }
    proxmox = {
      source  = "bpg/proxmox"
      version = "~> 0.83.0"
    }
    routeros = {
      source  = "terraform-routeros/routeros"
      version = "~> 1.99.0"
    }
    sops = {
      source  = "carlpett/sops"
      version = "~> 1.2.1"
    }
  }
}
