---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-outpost
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-outpost-secret
    template:
      data:
        AUTHENTIK_TOKEN: "{{ .OUTPOST_TOKEN }}"
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: authentik
