---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-outpost
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-outpost-secret
    template:
      data:
        AUTHENTIK_TOKEN: "{{ .OUTPOST_TOKEN }}"
        AUTHENTIK_POSTGRESQL__HOST: "postgres-vectorchord-rw.default.svc.cluster.local"
        AUTHENTIK_POSTGRESQL__PORT: "5432"
        AUTHENTIK_POSTGRESQL__USER: "authentik"
        AUTHENTIK_POSTGRESQL__NAME: "authentik"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .POSTGRESQL__PASSWORD }}"
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: authentik
