apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zeropod-system
resources:
  - namespace.yaml
  - migrations-crd.yaml
  - ca.yaml
  - rbac.yaml
  - runtimeclass.yaml
  - daemonset.yaml
