---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudbeaver-admin
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudbeaver-admin
    template:
      data:
        CB_SERVER_NAME: "CloudBeaver"
        CB_SERVER_URL: "https://cloudbeaver.sulibot.com"
        CB_ADMIN_NAME: '{{ .username | default "cbadmin" }}'
        CB_ADMIN_PASSWORD: "{{ .password }}"
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: default_admin
