---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudbeaver
spec:
  chartRef:
    kind: OCIRepository
    name: cloudbeaver
  interval: 1h
  timeout: 10m
  maxHistory: 3
  install:
    remediation:
      retries: 5
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
      strategy: rollback
    timeout: 10m
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      cloudbeaver:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/dbeaver/cloudbeaver
              tag: 26.0.0@sha256:53b446904be9cf7326e5cc446201aaaa35daa52e36887e46e38c70dde14b12e2
            env:
              TZ: America/Los_Angeles
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: &port 8978
                  initialDelaySeconds: 30
                  periodSeconds: 15
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 256Mi

    service:
      app:
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
          - IPv6
          - IPv4
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.sulibot.com"
        parentRefs:
          - name: gateway-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      workspace:
        existingClaim: "{{ .Release.Name }}-config"
        globalMounts:
          - path: /opt/cloudbeaver/workspace
