---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: soulsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: soulsync-secret
    template:
      data:
        SPOTIFY_CLIENT_ID: "{{ .SPOTIFY_CLIENT_ID }}"
        SPOTIFY_CLIENT_SECRET: "{{ .SPOTIFY_CLIENT_SECRET }}"
        SPOTIFY_REDIRECT_URI: "{{ .SPOTIFY_REDIRECT_URI }}"
  dataFrom:
    - extract:
        key: soulsync
