---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: soulsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: soulsync-secret
    template:
      data:
        SPOTIFY_CLIENT_ID: "{{ .SPOTIFY_CLIENT_ID }}"
        SPOTIFY_CLIENT_SECRET: "{{ .SPOTIFY_CLIENT_SECRET }}"
        SPOTIFY_REDIRECT_URI: "{{ .SPOTIFY_REDIRECT_URI }}"
        LASTFM_API_KEY: "{{ .LASTFM_API_KEY }}"
        LASTFM_API_SECRET: "{{ .LASTFM_API_SECRET }}"
  dataFrom:
    - extract:
        key: soulsync
  data:
    - secretKey: LASTFM_API_KEY
      remoteRef:
        key: last.fm
        property: API_KEY
    - secretKey: LASTFM_API_SECRET
      remoteRef:
        key: last.fm
        property: API_SECRET
