---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-nordvpn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbittorrent-nordvpn-secret
    template:
      data:
        VPN_SERVICE_PROVIDER: nordvpn
        VPN_TYPE: wireguard
        WIREGUARD_PRIVATE_KEY: '{{ index . "WIREGUARD_PRIVATE_KEY" | default (index . "NORDVPN_WIREGUARD_PRIVATE_KEY") }}'
        SERVER_COUNTRIES: '{{ index . "SERVER_COUNTRIES" | default "" }}'
        FIREWALL_INPUT_PORTS: "80,8081"
        TZ: America/Los_Angeles
  dataFrom:
    - extract:
        key: nordvpn
