---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller/ks.yaml
  - ./actual/ks.yaml
  - ./atuin/ks.yaml
  - ./authentik/ks.yaml
  - ./authentik-outpost/ks.yaml
  - ./autobrr/ks.yaml
  - ./bookshelf/ks.yaml
  - ./calibre-web-automated/ks.yaml
  - ./cloudbeaver/ks.yaml
  # cross-seed disabled
  # - ./cross-seed/ks.yaml
  # emby disabled
  # - ./emby/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./filebrowser/ks.yaml
  - ./firefly/ks.yaml
  - ./go2rtc/ks.yaml
  - ./home-assistant/ks.yaml
  - ./homepage/ks.yaml
  - ./immich/helm-repo/ks.yaml
  - ./immich/ks.yaml
  - ./immich-frame/ks.yaml
  # jellyseerr disabled
  # - ./jellyseerr/ks.yaml
  - ./karakeep/ks.yaml
  - ./kopia/ks.yaml
  - ./lazylibrarian/ks.yaml
  - ./lidarr/ks.yaml
  - ./matter-server/ks.yaml
  - ./miniflux/ks.yaml
  # mosquitto disabled
  # - ./mosquitto/ks.yaml
  - ./notifier/ks.yaml
  - ./nzbget/ks.yaml
  - ./ollama/ks.yaml
  - ./opencloud/ks.yaml
  - ./overseerr/ks.yaml
  - ./paperless/ks.yaml
  - ./paperless-gpt/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./radarr-4k/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  # sabnzbd disabled
  # - ./sabnzbd/ks.yaml
  - ./seerr/ks.yaml
  - ./shelfmark/ks.yaml
  # slskd disabled
  # - ./slskd/ks.yaml
  - ./smtp-relay/ks.yaml
  - ./sonarr-4k/ks.yaml
  - ./sonarr/ks.yaml
  - ./stirling-pdf/ks.yaml
  - ./tautulli/ks.yaml
  - ./tqm/ks.yaml
  - ./vikunja/ks.yaml
  # tuppr disabled
  # - ./tuppr/ks.yaml
  - ./volsync-repository-pvc/ks.yaml
  # zigbee disabled - pod Pending
  # - ./zigbee/ks.yaml
  # zwave disabled - pod Pending
  # - ./zwave/ks.yaml
