---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/serviceaccount.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-104-log-forwarder
  namespace: log-forwarding
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/rbac.authorization.k8s.io/clusterrole.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-104-log-forwarder
rules:
  - apiGroups: [""]
    resources:
      - events
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["events.k8s.io"]
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/rbac.authorization.k8s.io/clusterrolebinding.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-104-log-forwarder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-104-log-forwarder
subjects:
  - kind: ServiceAccount
    name: cluster-104-log-forwarder
    namespace: log-forwarding
