---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/service.json
apiVersion: v1
kind: Service
metadata:
  name: beyla
  labels:
    app.kubernetes.io/name: beyla
spec:
  selector:
    app.kubernetes.io/name: beyla
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
