---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pve-exporter-config
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pve-exporter-config
    creationPolicy: Owner
    template:
      data:
        pve.yml: |
          default:
            user: {{ .user | quote }}
            token_name: {{ .token_name | quote }}
            token_value: {{ .token_value | quote }}
            verify_ssl: false
  dataFrom:
    - extract:
        key: prometheus-pve-exporter
