---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: digarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: digarr-secret
    template:
      data:
        DATABASE_URL: "postgres://digarr:{{ .DATABASE_PASSWORD }}@postgres-vectorchord-rw.default.svc.cluster.local/digarr?sslmode=disable"
        DIGARR_ENCRYPTION_KEY: "{{ .DIGARR_ENCRYPTION_KEY }}"
        DIGARR_INITIAL_USERNAME: "{{ .DIGARR_INITIAL_USERNAME }}"
        DIGARR_INITIAL_PASSWORD: "{{ .DIGARR_INITIAL_PASSWORD }}"
        LIDARR_API_KEY: "{{ .LIDARR_API_KEY }}"
        AI_API_KEY: "{{ .OPENAI_API_KEY }}"
        LISTENBRAINZ_TOKEN: "{{ .LB_API_KEY }}"
        LASTFM_API_KEY: "{{ .LASTFM_API_KEY }}"
        SPOTIFY_CLIENT_ID: "{{ .SPOTIFY_CLIENT_ID }}"
        SPOTIFY_CLIENT_SECRET: "{{ .SPOTIFY_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: digarr
  data:
    - secretKey: LIDARR_API_KEY
      remoteRef:
        key: lidarr
        property: LIDARR_API_KEY
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: search-ops
        property: OPENAI_API_KEY
    - secretKey: SPOTIFY_CLIENT_ID
      remoteRef:
        key: soulsync
        property: SPOTIFY_CLIENT_ID
    - secretKey: SPOTIFY_CLIENT_SECRET
      remoteRef:
        key: soulsync
        property: SPOTIFY_CLIENT_SECRET
    - secretKey: LB_API_KEY
      remoteRef:
        key: MusicBrainz
        property: API_KEY
    - secretKey: LASTFM_API_KEY
      remoteRef:
        key: last.fm
        property: API_KEY
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: digarr-pg-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: digarr-pg-password
    template:
      data:
        username: digarr
        password: "{{ .DATABASE_PASSWORD }}"
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: digarr
        property: DATABASE_PASSWORD
