---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./targets.yaml
  - ./servicemonitor.yaml
  - ./prometheusrule.yaml
  - ./grafanadashboard.yaml
configMapGenerator:
  - name: openbao-dashboard
    files:
      - openbao.json
generatorOptions:
  disableNameSuffixHash: true
