# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "sops" {}

data "sops_file" "secrets" {
  source_file = "/Users/sulibot/repos/github/home-ops/terraform/infra/live/common/secrets.sops.yaml"
}

provider "cloudflare" {
  api_token = data.sops_file.secrets.data["cloudflare_api_token"]
}
