# inventory/host_vars/pve03.yml
ceph_db_lv_size: 11G
ceph_db_vg: ceph-db-vg

ceph_osd_ids:
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20

nvme_disk: /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_2TB_S59CNZFNB11046K
optane_disk: /dev/disk/by-id/nvme-INTEL_SSDPEK1A118GA_BTOC14120WNT118B

ceph_osds:
  - osd_id: 14
    data_device: /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_2TB_S59CNZFNB11046K-part1
    db_device: /dev/ceph-db-vg/osd14-db
    class: nvme
    expected_bluefs_db: false
  - osd_id: 15
    data_device: /dev/disk/by-id/wwn-0x5000c500e8685467-part1
    db_device: /dev/ceph-db-vg/osd15-db
    class: hdd
    drive_bucket: drive-pve03-1
    expected_bluefs_db: true
  - osd_id: 16
    data_device: /dev/disk/by-id/wwn-0x5000c500e8685467-part2
    db_device: /dev/ceph-db-vg/osd16-db
    class: hdd
    drive_bucket: drive-pve03-1
    expected_bluefs_db: true
  - osd_id: 17
    data_device: /dev/disk/by-id/wwn-0x5000c500e869e31a-part1
    db_device: /dev/ceph-db-vg/osd17-db
    class: hdd
    drive_bucket: drive-pve03-2
    expected_bluefs_db: true
  - osd_id: 18
    data_device: /dev/disk/by-id/wwn-0x5000c500e869e31a-part2
    db_device: /dev/ceph-db-vg/osd18-db
    class: hdd
    drive_bucket: drive-pve03-2
    expected_bluefs_db: true
  - osd_id: 19
    data_device: /dev/disk/by-id/wwn-0x5000c500e86ab39e-part1
    db_device: /dev/ceph-db-vg/osd19-db
    class: hdd
    drive_bucket: drive-pve03-3
    expected_bluefs_db: true
  - osd_id: 20
    data_device: /dev/disk/by-id/wwn-0x5000c500e86ab39e-part2
    db_device: /dev/ceph-db-vg/osd20-db
    class: hdd
    drive_bucket: drive-pve03-3
    expected_bluefs_db: true

sata_disks:
  - /dev/disk/by-id/wwn-0x5000c500e8685467
  - /dev/disk/by-id/wwn-0x5000c500e869e31a
  - /dev/disk/by-id/wwn-0x5000c500e86ab39e
