---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpa
spec:
  chart:
    spec:
      chart: vpa
      version: 4.10.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  interval: 1h
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    recommender:
      extraArgs:
        storage: prometheus
        prometheus-address: http://prometheus-operated.observability.svc.cluster.local:9090
        pod-recommendation-min-cpu-millicores: "10"
        pod-recommendation-min-memory-mb: "64"
        recommendation-margin-fraction: "0.15"
    updater:
      extraArgs:
        min-replicas: "1"
