---
apiVersion: v1
kind: Service
metadata:
  name: vpa-recommender-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vpa
    app.kubernetes.io/instance: vpa
    app.kubernetes.io/component: recommender
spec:
  selector:
    app.kubernetes.io/name: vpa
    app.kubernetes.io/instance: vpa
    app.kubernetes.io/component: recommender
  ports:
    - name: metrics
      port: 8942
      protocol: TCP
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: vpa-updater-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vpa
    app.kubernetes.io/instance: vpa
    app.kubernetes.io/component: updater
spec:
  selector:
    app.kubernetes.io/name: vpa
    app.kubernetes.io/instance: vpa
    app.kubernetes.io/component: updater
  ports:
    - name: metrics
      port: 8943
      protocol: TCP
      targetPort: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: vpa-admission-controller-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vpa
    app.kubernetes.io/instance: vpa
    app.kubernetes.io/component: admission-controller
spec:
  selector:
    app.kubernetes.io/name: vpa
    app.kubernetes.io/instance: vpa
    app.kubernetes.io/component: admission-controller
  ports:
    - name: metrics
      port: 8944
      protocol: TCP
      targetPort: metrics
