---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-vectorchord
  namespace: default
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17-0.4.3
  startDelay: 30
  stopDelay: 30
  switchoverDelay: 60

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  backup:
    volumeSnapshot:
      className: csi-rbd-rbd-vm-snapclass
      snapshotOwnerReference: backup

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: postgres-vectorchord-backup

  bootstrap:
    recovery:
      source: postgres-vectorchord
      database: immich
      owner: immich

  externalClusters:
    - name: postgres-vectorchord
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: postgres-vectorchord-backup

  managed:
    roles:
      - name: authentik
        login: true
        ensure: present
        passwordSecret:
          name: authentik-pg-password
      - name: firefly
        login: true
        ensure: present
        passwordSecret:
          name: firefly-pg-password
      - name: paperless
        login: true
        ensure: present
        passwordSecret:
          name: paperless-pg-password

  storage:
    size: 60Gi
    storageClass: csi-rbd-rbd-vm-sc-retain
