apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../databases
  - cluster.yaml
  - externalsecret-barman.yaml
  - objectstore.yaml
  - scheduledbackup.yaml
  - backup-verification-cronjob.yaml
