---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-tunnel-secret
    template:
      data:
        credentials.json: |-
          {{ toJson (dict "AccountTag" .CLOUDFLARE_ACCOUNT_TAG "TunnelID" .CLOUDFLARE_TUNNEL_ID "TunnelSecret" .CLOUDFLARE_TUNNEL_SECRET) }}
        config.yaml: |-
          tunnel: {{ .CLOUDFLARE_TUNNEL_ID }}
          credentials-file: /etc/cloudflared/credentials.json
          ingress:
            - hostname: external.sulibot.com
              originRequest:
                http2Origin: true
                noTLSVerify: true
                originServerName: sulibot.com
              service: https://cilium-gateway-gateway-tunnel.network.svc.cluster.local:443
            - service: http_status:404
  dataFrom:
    - extract:
        key: cloudflare
