---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onward-staging-private-artifacts
  namespace: engineering-staging
  labels:
    app.kubernetes.io/name: onward-staging
    app.kubernetes.io/part-of: onward
    environment: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-rbd-rbd-vm-sc-retain
