---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onward-staging
  namespace: engineering-staging
  labels:
    app.kubernetes.io/name: onward-staging
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: onward
    environment: staging
automountServiceAccountToken: false
