---
apiVersion: v1
kind: Service
metadata:
  name: onward-staging
  namespace: engineering-staging
  labels:
    app.kubernetes.io/name: onward-staging
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: onward
    environment: staging
spec:
  type: ClusterIP
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv6
    - IPv4
  selector:
    app.kubernetes.io/name: onward-staging
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
      appProtocol: http
