---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-vectorchord
  namespace: flux-system
  labels:
    layer: "data"
    component: database
    critical: "false"
spec:
  dependsOn:
    - name: postgres-vectorchord-recovery-precheck
      namespace: flux-system
    - name: cloudnative-pg
      namespace: flux-system
    - name: ceph-csi
      namespace: flux-system
  interval: ${TIER1_INTERVAL:=15m}
  retryInterval: ${TIER1_RETRY_INTERVAL:=30s}
  path: ./kubernetes/apps/tier-1-infrastructure/postgres-vectorchord/app-${CNPG_RECOVERY_MODE:=false}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: true
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: postgres-vectorchord
      namespace: default
    - apiVersion: postgresql.cnpg.io/v1
      kind: Database
      name: authentik
      namespace: default
    - apiVersion: postgresql.cnpg.io/v1
      kind: Database
      name: firefly
      namespace: default
