---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-dashboard-auth
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hermes-dashboard-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: HERMES_DASHBOARD_BASIC_AUTH_USERNAME
      remoteRef:
        key: hermes-dashboard
        property: HERMES_DASHBOARD_BASIC_AUTH_USERNAME
    - secretKey: HERMES_DASHBOARD_BASIC_AUTH_PASSWORD_HASH
      remoteRef:
        key: hermes-dashboard
        property: HERMES_DASHBOARD_BASIC_AUTH_PASSWORD_HASH
    - secretKey: HERMES_DASHBOARD_BASIC_AUTH_SECRET
      remoteRef:
        key: hermes-dashboard
        property: HERMES_DASHBOARD_BASIC_AUTH_SECRET
