# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {}

  required_providers {
    proxmox = { source = "bpg/proxmox", version = "~> 0.89.0" }
    sops    = { source = "carlpett/sops", version = "~> 1.3.0" }
  }
}

variable "region" {
  type        = string
  description = "Region identifier (injected by root terragrunt)"
  default     = "home-lab"
}

locals {
  ssh_public_key = file(pathexpand("~/.ssh/id_ed25519.pub"))
}

module "debtest01" {
  source = "../../../modules/debian_test_vm"

  vm_name = "debtest01"
  vm_id   = 10141

  proxmox = {
    node_name    = "pve01"
    datastore_id = "resources"
    vm_datastore = "rbd-vm"
  }

  vm_resources = {
    cpu_cores = 2
    memory_mb = 2048
    disk_gb   = 20
  }

  network = {
    bridge       = "vnet101"
    mtu          = 1450
    ipv4_address = "10.101.0.41"
    ipv4_netmask = "255.255.255.0"
    ipv4_gateway = "10.101.0.254"
    ipv6_address = "fd00:101::41"
    ipv6_prefix  = 64
    ipv6_gateway = "fd00:101::fffe"
  }

  loopback = {
    ipv4 = "10.101.254.41"
    ipv6 = "fd00:101:fe::41"
  }

  dns_servers = [
    "fd00:0:0:ffff::53",
    "10.255.0.53"
  ]

  frr_config = {
    enabled          = true
    local_asn        = 4210101041
    router_id        = "10.101.254.41"
    upstream_peer    = "fd00:101::fffe"
    upstream_asn     = 4200001000
    veth_enabled     = true
    veth_namespace   = "cilium"
    veth_ipv4_local  = "169.254.101.2"
    veth_ipv4_remote = "169.254.101.1"
    veth_ipv6_local  = "fd00:65:c111::2"
    veth_ipv6_remote = "fd00:65:c111::1"
  }

  ssh_public_key = local.ssh_public_key
}

output "debtest01_info" {
  value = {
    vm_id        = module.debtest01.vm_id
    vm_name      = module.debtest01.vm_name
    ipv4_address = module.debtest01.ipv4_address
    ipv6_address = module.debtest01.ipv6_address
    frr_asn      = module.debtest01.frr_asn
    ssh_command  = module.debtest01.ssh_command
  }
}

module "debtest02" {
  source = "../../../modules/debian_test_vm"

  vm_name = "debtest02"
  vm_id   = 10142

  proxmox = {
    node_name    = "pve02"
    datastore_id = "resources"
    vm_datastore = "rbd-vm"
  }

  vm_resources = {
    cpu_cores = 2
    memory_mb = 2048
    disk_gb   = 20
  }

  network = {
    bridge       = "vnet101"
    mtu          = 1450
    ipv4_address = "10.101.0.42"
    ipv4_netmask = "255.255.255.0"
    ipv4_gateway = "10.101.0.254"
    ipv6_address = "fd00:101::42"
    ipv6_prefix  = 64
    ipv6_gateway = "fd00:101::fffe"
  }

  loopback = {
    ipv4 = "10.101.254.42"
    ipv6 = "fd00:101:fe::42"
  }

  dns_servers = [
    "fd00:0:0:ffff::53",
    "10.255.0.53"
  ]

  frr_config = {
    enabled          = true
    local_asn        = 4210101042
    router_id        = "10.101.254.42"
    upstream_peer    = "fd00:101::fffe"
    upstream_asn     = 4200001000
    veth_enabled     = true
    veth_namespace   = "cilium"
    veth_ipv4_local  = "169.254.101.2"
    veth_ipv4_remote = "169.254.101.1"
    veth_ipv6_local  = "fd00:65:c111::2"
    veth_ipv6_remote = "fd00:65:c111::1"
  }

  ssh_public_key = local.ssh_public_key
}

output "debtest02_info" {
  value = {
    vm_id        = module.debtest02.vm_id
    vm_name      = module.debtest02.vm_name
    ipv4_address = module.debtest02.ipv4_address
    ipv6_address = module.debtest02.ipv6_address
    frr_asn      = module.debtest02.frr_asn
    ssh_command  = module.debtest02.ssh_command
  }
}

