---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: engineering-staging
  namespace: engineering-staging
  labels:
    app.kubernetes.io/name: engineering-staging
    app.kubernetes.io/part-of: engineering-platform
    environment: staging
spec:
  namespaceSelector:
    matchNames:
      - engineering-staging
  selector:
    matchLabels:
      cnpg.io/cluster: engineering-staging
      cnpg.io/podRole: instance
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
