apiVersion: ENC[AES256_GCM,data:dTM=,iv:Zv88DHNt1rR3FRGU3n0eORBgNJWV8CGu2hgPRSw2Ohc=,tag:4pMVKVUO9nkMYbiECVEw9A==,type:str]
kind: ENC[AES256_GCM,data:q7iO/VXN,iv:5bZFAM3jT4WondnBjKJOMKiXwolhsBlZQMgZw6CGxBA=,tag:w43IjmpiI+O4wLwMsGBFtA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BWfP5csaF3Y8eeQeCZUlceqwbmoFoyY=,iv:dqiDaCdbg2ZTzU/3fxGp6dewVAhYSZsS1YW3BNY7Q+Y=,tag:9p1iYsJtp2USegEaOrdcNw==,type:str]
    namespace: ENC[AES256_GCM,data:fR98c3VHMSdMXiVaC63F6hriDQ==,iv:DhFsFqTwSi3OnbvU5imOlxn/qqdM7GHzlnV/DN2rgNQ=,tag:4lHg7kl7kJk6mL79TAaRew==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:kitdJ9q18AtYbOnl+VE=,iv:pmjS5VfWcNCFVuo0q3nU/Q9JGGI+RkixuLqgnZQ+mrw=,tag:JKXsiR7naSVwcO724+xfhA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:wMoHyyk89/lMC1BFaQ==,iv:FtCLmiFuN6W3NSGUcVcPr/QnYlvwfy3Utn+spF7S1eQ=,tag:/Az3CMNa+Pj7pLBCyqBZKQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:lavcDVPIlwqIC33R8jk=,iv:3dBv7MstA3PYpBQvcLTAKuQKM4+vVP4g4Pr5LpBbg1M=,tag:ZpYdSR1687zFEELZJOzTsQ==,type:str]
type: ENC[AES256_GCM,data:/8QSi/r7,iv:EKM8MGsEabAjyp5eRwMBYA4+s/EBAXEzOz8Ma+W7390=,tag:QZxwMNPw7hZVDObUjfZu+A==,type:str]
stringData:
    anonKey: ENC[AES256_GCM,data:iLegb1xjA9N8MAnfKhbpeTzrvTHDhgOg1RQJNRJZYYJzKVX9WqMQQyEMdgMdTOJMZRvXUv+FO6ZZmKgRTKIwDO6v4+pEJVAKT5Y/ZzGAtLYDuO2AZ2XDokdqZah1lXxywBggmG9dwDlWj5PToClwKzZHQstX9cNTenwIb4p+vlks2xciDTtgAQUKTHdII9D7bIprfbmyiPYX8T9ObScG5NTEKTH3Dzedmw==,iv:bv9zBMyMrChn4Pmh/GPex7Me9WDlz9dUuqyOwOr509Q=,tag:TlVjWBHnJqTeigcbc1PiJw==,type:str]
    serviceKey: ENC[AES256_GCM,data:Qe4N83sI5MPEno6HCo1mvXnfULqVWzRICkFLQ1XenIjcfWekwr+mc3v95Flq9514jLOI3vfEK15ynxf4wioEc5Wzs81i/shGoM25AE9get/Z+HcYOrftr4nHLWsDtuRZxdmB0U0HAv0Y4FJoGDdqkzfqNdgOB5+h6PjL3x2InT8sLaMcYsZS8H07PxIfRsL2LbhnumWnzzMP9irlNs8nulmMVN0+nlK/KICm7qBHYqFSJRGV,iv:JJ4qfsAA1DlaSsvKzlbs99qJAkBdLR5mbaRUXbDoEJo=,tag:mQhYwPg2H23mH10UZbt4bg==,type:str]
    jwtSecret: ENC[AES256_GCM,data:u834hcgh1fwy2FTQVUkvYoxaP0+cTEYJPs9fm/G/cPajBOwxGM+lAyfGEM2RbZbRwHxe+1CS/NSJ6jBXUk7dpw==,iv:CSDPOeqAw6SXlBYRLecNq2AMWN+FpyPqlxPnAteZivE=,tag:ez22nlAkgobnGkSdQI2FYQ==,type:str]
    dbPassword: ENC[AES256_GCM,data:cOTJyb8KjVrm6S7p5Zm8Z38VqLYo7QawcOKVdxGbIFbE5+JE9J5mn2ZoHYHu1f6NasZe4N37W9g47V7+slEZGQ==,iv:M5R9bwRK2ycCjUZJcfnTUG+fVizQnxK9xrvSWxkOnws=,tag:nFFXxIkaOJ0rWZAQY02rKQ==,type:str]
    dbDatabase: ENC[AES256_GCM,data:boTUp5/qVDk=,iv:SJ8HhDeSYKJjsi1pV101Gqm03X9oRoutz0mfvD5noB0=,tag:xbTrs0kAZ1bEqQF/Pqqucw==,type:str]
    dashboardUsername: ENC[AES256_GCM,data:9PtUunW8E5Llgmz1v9k=,iv:HCBtnRvbeIdN0JxE86MxCwcQvvRz/i/s0CKues/czfU=,tag:SoNLwcP/Uc+MSIDD+Z6jQg==,type:str]
    dashboardPassword: ENC[AES256_GCM,data:9QnutoNjxtlhRuR0KHXpszy+jL64Q+bs3XUR5zK/vq90l8HU/P4txJU0NC7n8ijr,iv:GoRE0jAKj5iKxI0+ggDEqR7l2i4n3OIO3CTJBr+2UR4=,tag:ZAUXptm7vx2dUa3HdPo0qg==,type:str]
    openAiApiKey: ENC[AES256_GCM,data:BOLJ5X15gaE=,iv:FNUrV0ey2RqUD1v5DvixmyceEsexMNRs1oPARnFqV3Y=,tag:5u+fQVCK3sz+odqIIOTvqQ==,type:str]
    smtpUsername: ENC[AES256_GCM,data:fgqYvQ8vY04=,iv:pMuCzULLlUTuX+1Iej/g7jUGvYGCS6PDnZ5xnge3Tpo=,tag:RU340s9UP+Q3qqUfFawhQg==,type:str]
    smtpPassword: ENC[AES256_GCM,data:j0X8CCr1UQRlVAlub/5C7u1IW7g5yqLG6QKtW9Ci8iwx4zFYXNAUXrgBszFNtM8z,iv:auPAdBddqkQqT/nJs7XViGa4NPn81S8VbakYpUc+gBw=,tag:PuyRg5n4b9ANXOVPUYkIvQ==,type:str]
    s3KeyId: ENC[AES256_GCM,data:GtnaEsWKUOqxLSihyiF+JGYnUwsN8LLv8D3go14bc5k=,iv:Lim9NFcDzS8zb29OT5cGEzhMCM+mdYQLxKjW9BJ+BLQ=,tag:Byx659U8wrObmyCsscV7UA==,type:str]
    s3AccessKey: ENC[AES256_GCM,data:MRfgNHtTFqsTOMvswx3/edTKbAr1rPeFLFI+EhdIu2ZWl6Mu42XZ9YwTI79ZUCSsUGKxblRtEgffe9WauFhltw==,iv:x5J8j5S4QJwL5UG0qK6BWKKMB7wSJ3divRLs8/g8Wgs=,tag:Vewm/upjIbPY0gdk8vht+w==,type:str]
    realtimeSecretKeyBase: ENC[AES256_GCM,data:x0qPrceM1UoyMTCZWRFfXainWSg9CKNiB28VDCAIvooaPp0ylQZjUxjzbPuZWrF9xWjCrLzuOipbKR8r1lXJnsRJpCZL2AwIrRCPla0cIC8Msdmieiwe6A==,iv:1DHCzq2OYW3iHrH2AFxgna8aAh1EQdtRLw0TFu/wemQ=,tag:b5E+Rf2SPzhlcGXcJZL7rw==,type:str]
    realtimeDbEncKey: ENC[AES256_GCM,data:hv99A1i+AuFDuGxHAdna7g==,iv:VW5g+Z9vLuod7dW6V1sF6wVjJvzUq+2zzqWbFUycyeA=,tag:bSPfPWeEzSKwFXoQ41/h+w==,type:str]
    metaCryptoKey: ENC[AES256_GCM,data:scS0q9upsw3I7ROjz6+ZRmsVx4dL0n6WVA7v+VTW7ECXui+2goelFR2PegChMnUP68vtCPZ7PcDGEUoK6GF8HA==,iv:t0fB34IpBNZw8jlNagwPoMNj/GEro7P0UglPrUDdzDA=,tag:dFM1VDKgwozvnoYSt/fRvw==,type:str]
sops:
    hc_vault:
        - vault_address: https://openbao.sulibot.com
          engine_path: transit
          key_name: sops
          created_at: "2026-09-03T09:46:40Z"
          enc: vault:v1:36fIAFpQxo/66EGHz6doM83EjS55oUWTDDLGHaGZ/F/ofNH2YKnU/VsJc/5BxjdFcMWEsT+rFVXB/5am
    age:
        - recipient: age1k3sunyva3kc3jusxs3j93nyueqjgzcgg6s6qghn8aeqpuy7l35wss8gxvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZEVPU0NrWUJRNUFHbS9u
            UzJ3bzErbjlYdDlPNlJqQkhRZ1dyK0hoU1MwCnE3eUlvV0VZSEhJdkthcjk1c2NW
            SmtFNXpYeGhhMlJrRThpVSt5Z0MvQkkKLS0tIGdiUkxMV2Z2azBVaWc1SnI3Z2hQ
            SkRIZGlXOGU4WHc4UTZJdU9vREpxQlkKCnIJCLYjB9agSo43e9YkMN7+/nfmfacw
            9hT9a8svu72tqrCuzS5bTKFpFO+MvpZy96J7jHU7RzoF0IE84duwQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-03T09:46:40Z"
    mac: ENC[AES256_GCM,data:PByUviEu+yPMlz/VuQl0/fxqtVVnJ02KuqB2RfPlsxUzUIlF9U+5Bsfv0DUBQb0NlVFNtA3Ta3Oh67Y9GC2ZcGYNlQI9XUL8PaHmKB8iLHEON47dP07w1u3ioHesYw9af3cTNKtSfslaotMOcWKhlkK+B5at/NWPMP1Ra6RMyOg=,iv:oMeHmrvG3P97pdXu+NEhLbGdioh1FzDBZ7nb/xlZT1Q=,tag:SZw9eyA6jy7tggCehtrZHQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
