apiVersion: v1
kind: Secret
metadata:
    name: csi-ceph-opencloud-user-storage-secret
    namespace: ceph-csi
stringData:
    userID: opencloud-user-storage
    userKey: ENC[AES256_GCM,data:sGBJqrzygxL424jTJvAKsiiRjGHnJrUEynFCnWJxCat7DmsaexNIqQ==,iv:lzC9Ch2fv2W1rCXySe8DRV28lCcHCevk3SyNCErVG1g=,tag:esDJyggLvFSXjZdcUKex+g==,type:str]
sops:
    age:
        - recipient: age1k3sunyva3kc3jusxs3j93nyueqjgzcgg6s6qghn8aeqpuy7l35wss8gxvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPL0JhYUhQMDFPZlpldThT
            Ky90SzlPZWdnenFyQnJ0R0ZWN2kvdFlIcTNzCnpIZitoZEk0RUxZeEs0ZXlta3Nj
            SE81THFLT01GMTdtTFVEdUZBSThUdTAKLS0tIDhMRTFjTk5ESlU1MWNlNDNyNVNW
            d0FWbXQwNkxJbEZuTElSMGVGUUplVFUKAVeybp0Hdd+I53PoOi9eZGmc9xeGjhLO
            2N5idK2quQNbmcbZ/OFqUbwnNYRhuxepYIyKCRl0/dM0iBqfeuaJeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T06:20:25Z"
    mac: ENC[AES256_GCM,data:tL/9anyAlBUmoxJzYLCiiZRbPcku13vqvcsZmoTPhS7dC6C6fWA/6yphKVkt74BdvtE6uCQFnvk6oYBPJ97mbOHjgfas8VXY9Sb7L/PNPBeTet7DGty/doqoaMEM2GZ1EKl6OCnlZ2MRRySY2Wt16Te5RJcB5+C95O3dglCt7bM=,iv:gSKjXJvxIjr2Yysby2ZZBR9OULU9eAeaB6M3QpnUfjY=,tag:wn3SeYwfhSBsKMLj7DcHFg==,type:str]
    encrypted_regex: ^(userKey)$
    version: 3.12.1
