apiVersion: v1
kind: Secret
metadata:
    name: csi-ceph-syncthing-sulibot-secret
    namespace: ceph-csi
stringData:
    userID: syncthing-sulibot
    userKey: ENC[AES256_GCM,data:jR1FUw2jpYj0ZLYJS/j4cVY9xHva6dcAwd9TtiLQpXo2u0VokG+HKg==,iv:3ou8F8vILe6vZdLbC6P2Hr9XDGp3Kd1R9qT6Kb3FG+Q=,tag:VpXufu6mf1u/ZXiegR6zJQ==,type:str]
sops:
    age:
        - recipient: age1k3sunyva3kc3jusxs3j93nyueqjgzcgg6s6qghn8aeqpuy7l35wss8gxvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQUJReTg0WTE4US9rMG02
            UzJUWEp0T2srYTJnQzY1aXJwc1lQaUFucTNrCmlZT0R3dnhKMmxnRmZHdE1tdTJr
            dmwxeFlXN0Mxak8rN1ZPUXB1TlN3UVUKLS0tIHBjZlBabitjdnpXMHhFRkdtaGhU
            TkJOemVvb3NHTHEyUHc5b3NhbGp4MzAK82QqGdsKutzrDnRpFb2yssSlI99Ta+n1
            LCEmSkGRV5B2843acZ9GmwpLm0bq5JwACzVh4fb66T2ar9c5t6L9zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T06:20:25Z"
    mac: ENC[AES256_GCM,data:0b8U44VJMydGB838FECqqjXhhVYoGO+HuocRVOyhEAa04/BArRW0PP/NLUmOcOG8NX5JLGPmzLlGClfaD82jEQk/0WJYJnP1lc2sicCpMpiDv0Ko3CgYm8GmrJ7RPX5vGXZrLjmKVaQHaGBG7Kvv7c6zdtbkr0d8zCZqZkIJARE=,iv:g2+KiWow/Dn0Lu7DQlh2i/TvDkPQhHqKkQSh+y9CW7U=,tag:nvMgjzDFLi1opBMTX/AKXg==,type:str]
    encrypted_regex: ^(userKey)$
    version: 3.12.1
