---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-config
  namespace: observability
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-cephfs-config-sc
