---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calibre-web-automated-oidc
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: calibre-web-automated-oidc
    creationPolicy: Owner
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: authentik
        property: CALIBRE_WEB_AUTOMATED_OIDC_CLIENT_ID
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: authentik
        property: CALIBRE_WEB_AUTOMATED_OIDC_CLIENT_SECRET
