---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-automated-config
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-cephfs-config-sc
