apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - atuin.yaml
  - authentik.yaml
  - baserow.yaml
  - firefly.yaml
  - freshrss.yaml
  - paperless.yaml
  - vikunja.yaml
  - miniflux.yaml
  - n8n.yaml
  - radarr-main.yaml
  - radarr-log.yaml
  - radarr-4k-main.yaml
  - radarr-4k-log.yaml
  - sonarr-main.yaml
  - sonarr-log.yaml
  - sonarr-4k-main.yaml
  - sonarr-4k-log.yaml
  - twenty.yaml
