---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-log
  namespace: default
spec:
  cluster:
    name: postgres-vectorchord
  name: radarr_log
  owner: radarr
  ensure: present
