apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: vikunja
spec:
  name: vikunja
  owner: vikunja
  cluster:
    name: postgres-vectorchord
  ensure: present
  databaseReclaimPolicy: retain
