---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: whisparr
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: whisparr
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsOnly
        minAllowed:
          cpu: 50m
          memory: 256Mi
        maxAllowed:
          cpu: "4"
          memory: 4Gi
