---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filestash
spec:
  chartRef:
    kind: OCIRepository
    name: filestash
  interval: 1h
  timeout: 10m
  maxHistory: 3
  install:
    remediation:
      retries: 5
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
      strategy: rollback
    timeout: 10m
  values:
    controllers:
      filestash:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/machines/filestash
              tag: latest
            env:
              TZ: America/Los_Angeles
              APPLICATION_URL: "filestash.sulibot.com"
              CANARY: "true"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8334
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false # filestash runs as root
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
    service:
      app:
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
          - IPv6
          - IPv4
        ports:
          http:
            port: 80
            targetPort: *port
    route:
      app:
        hostnames:
          - filestash.sulibot.com
        parentRefs:
          - name: gateway-tunnel
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 80
    persistence:
      state:
        existingClaim: "{{ .Release.Name }}-config"
        globalMounts:
          - path: /app/data/state
      config-json:
        type: secret
        name: "{{ .Release.Name }}-secret"
        defaultMode: 0440
        globalMounts:
          - path: /app/data/state/config/config.json
            subPath: config.json
            readOnly: true
      content:
        type: persistentVolumeClaim
        existingClaim: csi-cephfs-content-pvc
        globalMounts:
          - path: /srv/data
            subPath: data
      tmp:
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /tmp
