---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-tunnel-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        credentials.json: >-
          {{ toJson (dict "AccountTag" .CLOUDFLARE_ACCOUNT_TAG "TunnelID" .CLOUDFLARE_TUNNEL_ID_CLUSTER_104 "TunnelSecret" .CLOUDFLARE_TUNNEL_SECRET_CLUSTER_104) }}
        config.yaml: |-
          tunnel: {{ .CLOUDFLARE_TUNNEL_ID_CLUSTER_104 }}
          credentials-file: /etc/cloudflared/credentials.json
          ingress:
            - hostname: hass.sulibot.com
              originRequest:
                http2Origin: true
                noTLSVerify: true
                originServerName: sulibot.com
              service: https://cilium-gateway-gateway-tunnel.network.svc.cluster.local:443
            - hostname: hass-app.sulibot.com
              originRequest:
                http2Origin: true
                noTLSVerify: true
                originServerName: sulibot.com
              service: https://cilium-gateway-gateway-tunnel.network.svc.cluster.local:443
            - hostname: ha-google.sulibot.com
              originRequest:
                http2Origin: true
                noTLSVerify: true
                originServerName: sulibot.com
              service: https://cilium-gateway-gateway-tunnel.network.svc.cluster.local:443
            - service: http_status:404
  dataFrom:
    - extract:
        key: cloudflare
