---
apiVersion: v1
kind: Service
metadata:
  name: cloudflare-tunnel
  namespace: network
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/part-of: cluster-104
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cloudflare-tunnel
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
