---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/serviceaccount.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-events
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/rbac.authorization.k8s.io/clusterrole.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-events
rules:
  - apiGroups: [""]
    resources:
      - events
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["events.k8s.io"]
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/rbac.authorization.k8s.io/clusterrolebinding.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-events
subjects:
  - kind: ServiceAccount
    name: fluent-bit-events
    namespace: observability
