---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fluent-bit-events
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit-events
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: metrics
      path: /api/v1/metrics/prometheus
      interval: 30s
      scrapeTimeout: 10s
