---
## yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: vikunja-dst
  labels:
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/component: backup-restore
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  kopia:
    repository: vikunja-volsync-secret
    sourceIdentity:
      sourceName: vikunja-src
      sourceNamespace: default
    copyMethod: Snapshot
    storageClassName: csi-cephfs-config-sc
    accessModes:
      - ReadWriteMany
    capacity: 5Gi
    volumeSnapshotClassName: csi-cephfs-config-snapclass
    cacheStorageClassName: csi-cephfs-config-sc
    cacheAccessModes:
      - ReadWriteMany
    cacheCapacity: 5Gi
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
