---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../app/alertmanagerconfig.yaml
  - ./prometheusrule-flux.yaml
  - ./prometheusrule-observability.yaml
  - ./prometheusrule-pods.yaml
