---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homeops-inventory-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: homeops-inventory-exporter
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
