---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets-ready
  namespace: flux-system
  labels:
    layer: "capability"
    component: secrets
    critical: "false"
spec:
  dependsOn:
    - name: external-secrets
      namespace: flux-system
    - name: onepassword
      namespace: flux-system
  interval: 15m
  retryInterval: 30s
  path: ./kubernetes/apps/tier-1-infrastructure/secrets-ready/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: flux-system
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets
      namespace: external-secrets
    - apiVersion: external-secrets.io/v1
      kind: ClusterSecretStore
      name: onepassword-connect
