---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: freshrss-secret
    creationPolicy: Owner
    template:
      data:
        DB_HOST: postgres-vectorchord-rw.default.svc.cluster.local
        DB_BASE: freshrss
        DB_USER: freshrss
        DB_PASSWORD: '{{ .FRESHRSS_DB_PASSWORD }}'
        OIDC_CLIENT_ID: '{{ index . "FRESHRSS_OIDC_CLIENT_ID" | default "freshrss" }}'
        OIDC_CLIENT_SECRET: '{{ .FRESHRSS_OIDC_CLIENT_SECRET }}'
        OIDC_CLIENT_CRYPTO_KEY: '{{ .FRESHRSS_OIDC_CLIENT_CRYPTO_KEY }}'
        config.custom.php: |
          <?php
          return [
            'http_auth_auto_register' => true,
            'http_auth_auto_register_email_field' => 'OIDC_CLAIM_email',
          ];
  dataFrom:
    - extract:
        key: freshrss
    - extract:
        key: authentik
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss-admin
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: freshrss-admin
    creationPolicy: Owner
    template:
      data:
        FRESHRSS_ADMIN_USERNAME: '{{ .username | default "admin@sulibot.com" }}'
        FRESHRSS_ADMIN_EMAIL: '{{ .username | default "admin@sulibot.com" }}'
        FRESHRSS_ADMIN_PASSWORD: '{{ .password }}'
        FRESHRSS_DEFAULT_USER: '{{ .username | default "admin@sulibot.com" }}'
  dataFrom:
    - extract:
        key: freshrss-admin
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freshrss-pg
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: freshrss-pg-password
    creationPolicy: Owner
    template:
      data:
        username: freshrss
        password: '{{ .FRESHRSS_DB_PASSWORD }}'
  dataFrom:
    - extract:
        key: freshrss
