github_token: ENC[AES256_GCM,data:IKM1uknL0hnYH3S3zaVlGKpAiBub2j/46rZtZcLoZjFTAYITM6AM2A==,iv:ZgbjKvXM5bmCCthaIJ1VDjGUGRr6Oy+nPlHHzJhclco=,tag:/AKFUfALnGViWVpa05SOvg==,type:str]
pve_endpoint: ENC[AES256_GCM,data:RMo4FEGvJ/nl/aRxDf7RHBE30/8sgVHUNadK7FLJ1IXopT7L0KQgbA==,iv:g4+Phpt6s/AwSGWZdOHwoL/DegyKGfXLZXtmqMJsjpY=,tag:F+rK8O3q3w20z9xyqlQ+zA==,type:str]
pve_api_token_id: ENC[AES256_GCM,data:aiPmgPwmSx1HRlpqd67Gc3EGOHQYUA==,iv:tioXlgQ72/ELkksqYlisF3m0zoXxQMYwLtsUDA458BI=,tag:k/LVhq1wc1qjyuoyHpsVug==,type:str]
pve_api_token_secret: ENC[AES256_GCM,data:spGlDtytqaj11Ns3lQF8UXCOs+CFxg96FcfBsflqB0mxgQIl,iv:8+gGlrJrjhQ/kOkBAwR6/fS7FBS6jZmPLw9YnlY+kFw=,tag:Q3pmFhH4GMF0Sr1sPVXXTQ==,type:str]
pve_username: root@pam
pve_password: ENC[AES256_GCM,data:+kNIw4y4/OA=,iv:3SUcmCbK1ell2RzNQteLJgF4MRwam9pSuBioG3HGlf8=,tag:a3KqssgKy8eB37tXAj2QRw==,type:str]
vm_password: ENC[AES256_GCM,data:7gkgcdYfTac=,iv:bV/3IQLO0DceY+VuLFGbQ/iDYkncs7rca2WkOACARRk=,tag:5MdLG0kU0x88cmdyBnofIQ==,type:str]
routeros_username: admin
routeros_password: ENC[AES256_GCM,data:41IGnVBBoJI=,iv:ibzIktsf92qn3Vx6F14LMojc/0VlObmvdW2PRlzhhr0=,tag:aX7SZ8uyrQsDaPC0elqHwQ==,type:str]
routeros_test_username: admin
routeros_test_password: ENC[AES256_GCM,data:oyLw2S5RYUs=,iv:rlp3HTPiRVifc6Ub8xk8hSBbG30mxDNL3mkCeddXsyg=,tag:a3hLPyPIasHAOhzZIU1l9g==,type:str]
routeros_hosturl: https://10.30.0.254
routeros_test_hosturl: https://10.200.0.250
acme_contact_email: sulibot@gmail.com
cloudflare_api_token: ENC[AES256_GCM,data:fwPxZJUa97Fg9DVRakhE3zBrHbT1R+4S47jgtzvwmQx/UQt2Vgwfvw==,iv:X1aE+GzIIS3FKhdu/WH9S64pieAowydu6HE8UYNbPrw=,tag:TxtF5JeOO+48+U96DreByQ==,type:str]
cloudflare_account_id: 089ac5ef7a1525cb7d7129cdde5873cd
minio_root_user: minioadmin
minio_root_password: ENC[AES256_GCM,data:DFxA1Mwe9epQFrwlQmSO8SRcLVyBPX7gOlu4LLzgvDg=,iv:ItEowv7ZxVRQuTjZE0FFenrJ6jvUuSugt3EdQ9dp7ow=,tag:T/hFjprlJ8gMC0pdDLI1aA==,type:str]
minio_barman_access_key: cnpg-barman
minio_barman_secret_key: ENC[AES256_GCM,data:YKOXSOcDxbvTalUr/V/wM67CB3UjcGhEDHF6EcGCtqSW9CwSTG5kZQ==,iv:LU1b09+iVODqFya36KMXdy5LYFnvhg6lWWZnnjpQ08U=,tag:R4dwzMMPLxBR2VOFFXf+8g==,type:str]
cf_access_client_id: bc361f95-ddf8-4826-9cb7-402a2a8a769d
cf_access_client_secret: ENC[AES256_GCM,data:JyorIMNHmA5NovQLs61M/P3njnuDmpmFmDfc4v+5+sTBFUexoRr5c0OhrQupHdoG2Ql3AfSEKtTCglW1hK3Biw==,iv:LIExyhJeeIq6WGXi3od2vJvlqfuuI0IjU1PhN2hTaSc=,tag:s70a5VSNm9zv70LEoXZUaw==,type:str]
cf_access_allowed_emails: sulibot@gmail.com admin@sulibot.com bcwallace@gmail.com bodawee@gmail.com sulaiman.ahmad@gmail.com
cloudflare_zone_id: 2fc344221774a596036a4303011c7921
cloudflare_tunnel_id: 0977043f-80e9-4549-a6f0-0af145a17f27
otbr_thread_dataset_secret: ENC[AES256_GCM,data:dS3G9Rz1WOg2pRCnSrrjEpyGEIC0Na8RupHMxzGbKg9jkVDg3v31bLZUmUg1Yc6ciB1EKcEUwW2ZDOnPNURfzfIZcsf8WNNRCBKpDq0qSxAdNMXKchIGlqmo/P/XnryvMzYD10uMequzPBTxCm80J3cT6wdN5Gp8ljMnxN8wAd1rXJ92uKDsM9rnCt2qwxUQRxbVh0ARtPGEtzkbU4TvXSOU4Wkqne+W7xJNXUNdCaTN6dc7n5DsJ8O3OZwz9CTo9WZjJBglRCWvGeOvVFOhiFIehRX7UKdf,iv:t6+ty9J3dqmligyv/hCGnI65Nsd1g77BmoUIwKQKnb0=,tag:FR0nXpqhwpZnwqARtlehdQ==,type:str]
sops:
    age:
        - recipient: age1k3sunyva3kc3jusxs3j93nyueqjgzcgg6s6qghn8aeqpuy7l35wss8gxvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieFhnTitNdWswMHV4Qi9H
            cFhwNGJzRUwvcmtoWlZxREVodW1vZzdtNGpJCjdVVHJTLzdXTlptYUR0aTVWQ3Q0
            VmtRV1hDbEU5MTBEN1NEdTlSS2xaVUUKLS0tIGVyNmlGNllGdnlxaG51Qmxud21z
            N1JiU2d1NzQwZVJxSnNmeXVwYkQ2RG8KGTp1oL4Gpzpnj1lSYDsvFDnAkGBro7xD
            UvVPdq0e7UdChCVmjAU8JgrYfMa0VEvrCHiTsfVj9JP6LN65Rr7CAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T06:48:49Z"
    mac: ENC[AES256_GCM,data:QAXGA8kb9vAXbMLTfl/k4M/asDa+gpBHn1pUau1vQrBODe1WvjLCpybOja/6NbFnw3BW67ql80s6YB81EWQ+B/Vok8Iqq56SBgXH0MYKsOzVF3Sq5k5UcbI0crwfFyDuneMEcQZxF1JpmeivR/ktvxwd2Ph71jau9owmeRfOjfQ=,iv:UStXKn9Ifh4ZF+ioOhMJduGnrHdNx4wJrNZGVnWZXKw=,tag:WyRI2ju8L9mwjkNao4yaNg==,type:str]
    encrypted_regex: ^(data|stringData|.*secret.*|.*token.*|.*password.*|.*endpoint)$
    version: 3.10.2
