---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencloud
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: opencloud-secret
    creationPolicy: Owner
    template:
      data:
        IDM_ADMIN_USERNAME: '{{ index . "IDM_ADMIN_USERNAME" | default .username | default "admin" }}'
        IDM_ADMIN_PASSWORD: '{{ index . "IDM_ADMIN_PASSWORD" | default .password }}'
  dataFrom:
    - extract:
        key: opencloud
    - extract:
        key: default_admin
