---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./flux-system
  - ../../apps/tier-0-foundation/external-secrets
  - ./multus
  - ./cilium-bgp
  - ./network
  - ./cloudflare-tunnel
  - ./external-dns
  - ./storage
  - ./matter-server
  - ./music-assistant
  - ./otbr
