# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {}

  required_providers {
    proxmox  = { source = "bpg/proxmox", version = "~> 0.98.0" }
    sops     = { source = "carlpett/sops", version = "~> 1.4.0" }
    null     = { source = "hashicorp/null", version = "~> 3.0" }
    routeros = { source = "terraform-routeros/routeros", version = "~> 1.99.0" }
  }
}

variable "region" {
  type    = string
  default = "home-lab"
}

locals {
  ssh_public_key = file(pathexpand("~/.ssh/id_ed25519.pub"))
  host_domain    = "otbr01.sulibot.com"
  service_domain = "otbr.sulibot.com"
  container_ipv4 = "10.31.0.253"
  container_ipv6 = "fd00:31::253"

  containers = {
    otbr01 = {
      vm_id       = 30253
      node_name   = "pve01"
      hostname    = "otbr01"
      description = "OpenThread Border Router LXC on pve01 using SONOFF ZBDongle-E RCP"
      started     = false
      cpu_cores   = 2
      memory_mb   = 2048
      swap_mb     = 512
      disk_gb     = 16
      bridge      = "vmbr0"
      vlan_id     = 31
      firewall    = false
      features = {
        nesting = true
        keyctl  = true
      }
      ipv4_address    = "10.31.0.253/24"
      ipv4_gateway    = "10.31.0.254"
      ipv6_address    = "fd00:31::253/64"
      ipv6_gateway    = "fd00:31::fffe"
      ssh_public_keys = [local.ssh_public_key]
      tags            = ["thread", "matter", "otbr", "lxc", "trixie"]
      mount_points = [
        {
          volume = "rbd-vm"
          size   = "8G"
          path   = "/var/lib/otbr"
        }
      ]
    }
  }

  otbr_provision_commands = [
    "set -euo pipefail",
    "export DEBIAN_FRONTEND=noninteractive",
    "apt-get update -qq >/dev/null",
    "apt-get install -y -qq --no-install-recommends ca-certificates curl git iproute2 jq lsb-release sudo >/dev/null",
    "mkdir -p /etc/iproute2",
    "touch /etc/iproute2/rt_tables",
    "mkdir -p /var/lib/otbr",
    "if [ ! -d /opt/ot-br-posix/.git ]; then git clone https://github.com/openthread/ot-br-posix /opt/ot-br-posix >/dev/null 2>&1; fi",
    "cd /opt/ot-br-posix && git fetch --tags --force >/dev/null 2>&1 && git checkout -f thread-reference-20250612 >/dev/null 2>&1 && git submodule update --init --recursive --depth 1 >/dev/null 2>&1 || git submodule update --init --recursive >/dev/null 2>&1",
    "cd /opt/ot-br-posix && OTBR_MDNS=avahi WEB_GUI=1 NAT64=0 BORDER_ROUTING=1 INFRA_IF_NAME=eth0 ./script/bootstrap",
    "cd /opt/ot-br-posix && ./script/cmake-build -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=/usr -DOTBR_DBUS=ON -DOTBR_DNSSD_DISCOVERY_PROXY=ON -DOTBR_INFRA_IF_NAME=eth0 -DOTBR_MDNS=avahi -DOTBR_VERSION= -DOT_PACKAGE_VERSION= -DOTBR_SRP_ADVERTISING_PROXY=ON -DOTBR_WEB=ON -DOTBR_BORDER_ROUTING=ON -DOTBR_REST=ON -DOTBR_BACKBONE_ROUTER=ON -DOT_FIREWALL=ON",
    "cd /opt/ot-br-posix/build/otbr && ninja",
    "cd /opt/ot-br-posix/build/otbr && ninja install",
    "test -x /usr/sbin/otbr-agent",
    "test -x /etc/init.d/otbr-agent",
    "cat > /etc/default/otbr-agent <<'CONF'\nOTBR_AGENT_OPTS=\"-I wpan0 -B eth0 -d 7 spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=460800 trel://eth0\"\nCONF",
    "systemctl daemon-reload",
    "systemctl enable otbr-agent",
    "systemctl enable otbr-web",
    "systemctl start otbr-agent",
    "for i in $(seq 1 12); do systemctl is-active --quiet otbr-agent && break || sleep 5; done",
    "systemctl start otbr-web",
    "for i in $(seq 1 24); do systemctl is-active --quiet otbr-agent && systemctl is-active --quiet otbr-web && break || sleep 5; done",
    "systemctl is-active --quiet otbr-agent",
    "systemctl is-active --quiet otbr-web",
    "timeout 10 ot-ctl state >/dev/null",
    "journalctl -u otbr-agent --no-pager -n 20 | tail -n 20",
  ]
}

module "otbr_lxc" {
  source = "../../../modules/proxmox_lxc_role"

  proxmox = {
    datastore_id = "resources"
    vm_datastore = "rbd-vm"
  }

  template = {
    download  = false
    url       = ""
    file_name = ""
    file_id   = "resources:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
  }

  dns_servers = [
    "fd00:0:0:ffff::53",
    "10.255.0.53",
  ]

  containers = local.containers

  provision = {
    enabled            = false
    ssh_user           = "root"
    ssh_private_key    = ""
    ssh_timeout        = "10m"
    wait_for_cloudinit = false
    commands           = []
  }
}

resource "null_resource" "otbr_host_config" {
  depends_on = [module.otbr_lxc]

  triggers = {
    container_id = module.otbr_lxc.containers["otbr01"].id
    vm_id        = "30253"
    rcp_device   = "/dev/ttyACM0"
  }

  connection {
    type        = "ssh"
    user        = "root"
    private_key = file(pathexpand("~/.ssh/id_ed25519"))
    host        = "10.10.0.1"
    timeout     = "10m"
  }

  provisioner "remote-exec" {
    inline = [
      "pct stop 30253 >/dev/null 2>&1 || true",
      "pct set 30253 --onboot 1 --dev0 path=/dev/net/tun --dev1 path=/dev/ttyACM0",
      "pct start 30253",
      "for i in $(seq 1 24); do pct exec 30253 -- sh -lc 'test -e /dev/net/tun && test -e /dev/ttyACM0' && break || sleep 5; done",
      "pct exec 30253 -- sh -lc 'test -e /dev/net/tun && test -e /dev/ttyACM0'",
    ]
  }
}

resource "null_resource" "otbr_provision" {
  depends_on = [null_resource.otbr_host_config]

  triggers = {
    container_id = module.otbr_lxc.containers["otbr01"].id
    commands_sha = sha256(join("\n", local.otbr_provision_commands))
  }

  connection {
    type        = "ssh"
    user        = "root"
    private_key = file(pathexpand("~/.ssh/id_ed25519"))
    host        = local.container_ipv4
    timeout     = "15m"
  }

  provisioner "remote-exec" {
    inline = local.otbr_provision_commands
  }
}

output "otbr_lxc_containers" {
  value = module.otbr_lxc.containers
}

output "otbr_endpoints" {
  value = {
    host    = local.host_domain
    service = local.service_domain
    ipv4    = local.container_ipv4
    ipv6    = local.container_ipv6
  }
}

resource "routeros_ip_dns_record" "otbr_host_ipv4" {
  name    = local.host_domain
  type    = "A"
  address = local.container_ipv4
  ttl     = "5m"
  comment = "managed by terraform otbr-lxc"
}

resource "routeros_ip_dns_record" "otbr_host_ipv6" {
  name    = local.host_domain
  type    = "AAAA"
  address = local.container_ipv6
  ttl     = "5m"
  comment = "managed by terraform otbr-lxc"
}

resource "routeros_ip_dns_record" "otbr_service_cname" {
  name    = local.service_domain
  type    = "CNAME"
  cname   = local.host_domain
  ttl     = "5m"
  comment = "managed by terraform otbr-lxc"
}
