# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {}

  required_providers {
    proxmox  = { source = "bpg/proxmox", version = "~> 0.98.0" }
    sops     = { source = "carlpett/sops", version = "~> 1.4.0" }
    null     = { source = "hashicorp/null", version = "~> 3.0" }
    routeros = { source = "terraform-routeros/routeros", version = "~> 1.99.0" }
  }
}

variable "region" {
  type    = string
  default = "home-lab"
}

variable "smallstep_ca_password" {
  type      = string
  sensitive = true
}

variable "smallstep_provisioner_password" {
  type      = string
  sensitive = true
}

locals {
  ssh_public_key            = file(pathexpand("~/.ssh/id_ed25519.pub"))
  kanidm_unix_auth_commands = ["mkdir -p /etc/kanidm", "chmod 755 /etc/kanidm", "apt-get install -y -qq --no-install-recommends kanidm-unixd-clients \u003e/dev/null 2\u003e\u00261 || apt-get install -y -qq --no-install-recommends kanidm-unixd \u003e/dev/null", "cat \u003e /etc/kanidm/config \u003c\u003c'CFG'\nuri = \"https://idm.sulibot.com\"\nCFG", "cat \u003e /etc/kanidm/unixd \u003c\u003c'CFG'\nversion = \"2\"\n[kanidm]\npam_allowed_login_groups = [\"posix_group\"]\nCFG", "chmod 600 /etc/kanidm/config /etc/kanidm/unixd", "systemctl enable --now kanidm-unixd \u003e/dev/null 2\u003e\u00261 || true", "systemctl enable --now kanidm-unixd-tasks \u003e/dev/null 2\u003e\u00261 || true"]
  host_domain               = "pki01.sulibot.com"
  service_domain            = "pki.sulibot.com"
  step_cli_version          = "0.30.1"
  step_ca_version           = "0.30.1"

  containers = {
    pki01 = {
      vm_id       = 100064
      node_name   = "pve01"
      hostname    = "pki01"
      description = "Smallstep PKI LXC on pve01 (tenant 100)"
      cpu_cores   = 2
      memory_mb   = 2048
      swap_mb     = 512
      disk_gb     = 16
      bridge      = "vnet100"
      vlan_id     = null
      firewall    = false
      features = {
        nesting = true
        keyctl  = true
      }
      ipv4_address    = "10.100.0.64/24"
      ipv4_gateway    = "10.100.0.254"
      ipv6_address    = "fd00:100::64/64"
      ipv6_gateway    = "fd00:100::fffe"
      ssh_public_keys = [local.ssh_public_key]
      tags            = ["identity", "pki", "smallstep", "lxc", "trixie"]
      mount_points = [
        {
          volume = "rbd-vm"
          size   = "20G"
          path   = "/var/lib/step-ca"
        }
      ]
    }
  }

  smallstep_provision_commands = concat(local.kanidm_unix_auth_commands, [
    "export DEBIAN_FRONTEND=noninteractive",
    "apt-get update -qq >/dev/null",
    "apt-get install -y -qq --no-install-recommends curl ca-certificates jq tar >/dev/null",
    "curl -fsSL -o /tmp/step-cli.deb https://dl.smallstep.com/gh-release/cli/docs-cli-install/v${local.step_cli_version}/step-cli_${local.step_cli_version}-1_amd64.deb",
    "dpkg -i /tmp/step-cli.deb >/dev/null",
    "rm -f /tmp/step-cli.deb",
    "curl -fsSL -o /tmp/step-ca.deb https://dl.smallstep.com/gh-release/certificates/docs-ca-install/v${local.step_ca_version}/step-ca_${local.step_ca_version}-1_amd64.deb",
    "dpkg -i /tmp/step-ca.deb >/dev/null",
    "rm -f /tmp/step-ca.deb",
    "id step-ca >/dev/null 2>&1 || useradd --system --home-dir /var/lib/step-ca --create-home --shell /usr/sbin/nologin step-ca",
    "mkdir -p /etc/step-ca /etc/step-ca/secrets /var/lib/step-ca/db /var/lib/step-ca/certs /var/lib/step-ca/config",
    "printf '%s' '${var.smallstep_ca_password}' > /etc/step-ca/secrets/password.txt",
    "printf '%s' '${var.smallstep_provisioner_password}' > /etc/step-ca/secrets/provisioner-password.txt",
    "chmod 600 /etc/step-ca/secrets/password.txt /etc/step-ca/secrets/provisioner-password.txt",
    "if [ ! -f /var/lib/step-ca/config/ca.json ]; then export STEPPATH=/var/lib/step-ca && step ca init --name 'Sulibot Homelab PKI' --deployment-type standalone --dns '${local.service_domain},${local.host_domain}' --address '127.0.0.1:9000' --provisioner 'admin@sulibot.com' --password-file /etc/step-ca/secrets/password.txt --provisioner-password-file /etc/step-ca/secrets/provisioner-password.txt --acme; fi",
    "mkdir -p /etc/step-ca/certs /etc/step-ca/config /etc/step-ca/db",
    "cp -f /var/lib/step-ca/certs/root_ca.crt /etc/step-ca/certs/root_ca.crt",
    "cp -f /var/lib/step-ca/certs/intermediate_ca.crt /etc/step-ca/certs/intermediate_ca.crt",
    "cp -f /var/lib/step-ca/secrets/intermediate_ca_key /etc/step-ca/secrets/intermediate_ca_key",
    "cp -f /var/lib/step-ca/config/ca.json /etc/step-ca/config/ca.json",
    "cp -f /var/lib/step-ca/db/db /etc/step-ca/db/db",
    "chown -R step-ca:step-ca /etc/step-ca /var/lib/step-ca",
    "chmod 600 /etc/step-ca/secrets/password.txt /etc/step-ca/secrets/provisioner-password.txt /etc/step-ca/secrets/intermediate_ca_key",
    "cat > /etc/systemd/system/step-ca.service <<'UNIT'\n[Unit]\nDescription=Smallstep Certificate Authority\nAfter=network-online.target\nWants=network-online.target\n\n[Service]\nType=simple\nUser=step-ca\nGroup=step-ca\nEnvironment=STEPPATH=/etc/step-ca\nExecStart=/usr/bin/step-ca /etc/step-ca/config/ca.json --password-file /etc/step-ca/secrets/password.txt\nRestart=on-failure\nRestartSec=5s\nAmbientCapabilities=CAP_NET_BIND_SERVICE\nCapabilityBoundingSet=CAP_NET_BIND_SERVICE\nNoNewPrivileges=true\n\n[Install]\nWantedBy=multi-user.target\nUNIT",
    "systemctl daemon-reload",
    "systemctl enable --now step-ca",
    "systemctl restart step-ca",
    "for i in $(seq 1 30); do curl -ksS -o /dev/null https://127.0.0.1:9000/health && exit 0; sleep 2; done; systemctl --no-pager --full status step-ca; exit 1",
  ])
}

module "smallstep_lxc" {
  source = "../../../modules/proxmox_lxc_role"

  proxmox = {
    datastore_id = "resources"
    vm_datastore = "rbd-vm"
  }

  template = {
    download  = false
    url       = ""
    file_name = ""
    file_id   = "resources:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
  }

  dns_servers = [
    "fd00:0:0:ffff::53",
    "10.255.0.53",
  ]

  containers = local.containers

  provision = {
    enabled            = true
    ssh_user           = "root"
    ssh_private_key    = file(pathexpand("~/.ssh/id_ed25519"))
    ssh_timeout        = "10m"
    wait_for_cloudinit = false
    commands           = local.smallstep_provision_commands
  }
}

output "smallstep_lxc_containers" {
  value = module.smallstep_lxc.containers
}

output "smallstep_endpoint" {
  value = "https://pki.sulibot.com"
}

resource "null_resource" "smallstep_caddy_frontend" {
  depends_on = [module.smallstep_lxc]

  triggers = {
    container_id    = module.smallstep_lxc.containers["pki01"].id
    service_domain  = local.service_domain
    cloudflare_hash = sha256(data.sops_file.secrets.data["cloudflare_api_token"])
  }

  connection {
    type        = "ssh"
    user        = "root"
    private_key = file(pathexpand("~/.ssh/id_ed25519"))
    host        = "10.100.0.64"
    timeout     = "10m"
  }

  provisioner "file" {
    content     = <<-EOT
CF_Token=${data.sops_file.secrets.data["cloudflare_api_token"]}
EOT
    destination = "/root/cloudflare.env"
  }

  provisioner "remote-exec" {
    inline = ["export DEBIAN_FRONTEND=noninteractive", "apt-get update -qq \u003e/dev/null", "apt-get install -y -qq --no-install-recommends caddy curl openssl \u003e/dev/null", "mkdir -p /etc/caddy/certs /etc/systemd/system/caddy.service.d /root/.acme.sh", "cat \u003e /etc/systemd/system/caddy.service.d/override.conf \u003c\u003c'UNIT'\n[Service]\nPrivateTmp=false\nPrivateDevices=false\nProtectSystem=no\nProtectHome=false\nNoNewPrivileges=false\nUNIT", "if [ ! -x /root/.acme.sh/acme.sh ]; then curl -fsSL https://get.acme.sh | sh -s email=admin@sulibot.com \u003e/dev/null; fi", "set -a \u0026\u0026 . /root/cloudflare.env \u0026\u0026 set +a", "/root/.acme.sh/acme.sh --set-default-ca --server letsencrypt \u003e/dev/null", "/root/.acme.sh/acme.sh --issue --dns dns_cf -d pki.sulibot.com --keylength ec-256 --force", "/root/.acme.sh/acme.sh --install-cert -d pki.sulibot.com --ecc --fullchain-file /etc/caddy/certs/pki.sulibot.com.crt --key-file /etc/caddy/certs/pki.sulibot.com.key", "shred -u /root/cloudflare.env || rm -f /root/cloudflare.env", "chown root:caddy /etc/caddy/certs/pki.sulibot.com.crt /etc/caddy/certs/pki.sulibot.com.key", "chmod 640 /etc/caddy/certs/pki.sulibot.com.crt /etc/caddy/certs/pki.sulibot.com.key", "cat \u003e /etc/caddy/Caddyfile \u003c\u003c'CFG'\n{\n  admin off\n}\n\npki.sulibot.com {\n  tls /etc/caddy/certs/pki.sulibot.com.crt /etc/caddy/certs/pki.sulibot.com.key\n  reverse_proxy https://127.0.0.1:9000 {\n    transport http {\n      tls_insecure_skip_verify\n    }\n  }\n}\nCFG", "systemctl daemon-reload", "systemctl enable --now caddy", "systemctl restart caddy", "curl --resolve pki.sulibot.com:443:127.0.0.1 -ksS -o /dev/null https://pki.sulibot.com/health"]
  }
}

resource "routeros_ip_dns_record" "smallstep_host_ipv4" {
  name    = local.host_domain
  type    = "A"
  address = "10.100.0.64"
  ttl     = "5m"
  comment = "managed by terraform smallstep-lxc"
}

resource "routeros_ip_dns_record" "smallstep_host_ipv6" {
  name    = local.host_domain
  type    = "AAAA"
  address = "fd00:100::64"
  ttl     = "5m"
  comment = "managed by terraform smallstep-lxc"
}

resource "routeros_ip_dns_record" "smallstep_service_cname" {
  name    = local.service_domain
  type    = "CNAME"
  cname   = local.host_domain
  ttl     = "5m"
  comment = "managed by terraform smallstep-lxc"
}

resource "null_resource" "smallstep_1password_sync" {
  depends_on = [module.smallstep_lxc, null_resource.smallstep_caddy_frontend]

  triggers = {
    service_domain = local.service_domain
    sync_rev       = "smallstep-1password-v1"
  }

  provisioner "local-exec" {
    command = <<-OPCMD
      set -euo pipefail
      SSH_OPTS="-i $HOME/.ssh/id_ed25519 -o BatchMode=yes -o ConnectTimeout=8 -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"

      timeout 10 op whoami >/dev/null 2>&1 || { echo "Skipping 1Password PKI sync: 1Password CLI is not authenticated or is waiting for interactive unlock"; exit 0; }

      ITEM_ID="$(timeout 10 op item get "smallstep-pki" --vault "Kubernetes" --format json 2>/dev/null | jq -r '.id' || true)"
      if [ -z "$ITEM_ID" ] || [ "$ITEM_ID" = "null" ]; then
        ITEM_ID="$(timeout 15 op item create \
          --vault="Kubernetes" \
          --title="smallstep-pki" \
          --category=server \
          "hostname[text]=pki.sulibot.com" \
          "host_node[text]=pki01.sulibot.com" \
          "ca_url[text]=https://pki.sulibot.com" \
          --format json | jq -r '.id' || true)"
      fi

      if [ -z "$ITEM_ID" ] || [ "$ITEM_ID" = "null" ]; then
        echo "Skipping 1Password PKI sync: unable to read or create item smallstep-pki in vault Kubernetes"
        exit 0
      fi

      ROOT_CRT="$(timeout 20 ssh $SSH_OPTS root@10.100.0.64 'cat /etc/step-ca/certs/root_ca.crt')"
      INTERMEDIATE_CRT="$(timeout 20 ssh $SSH_OPTS root@10.100.0.64 'cat /etc/step-ca/certs/intermediate_ca.crt')"
      INTERMEDIATE_KEY_B64="$(timeout 20 ssh $SSH_OPTS root@10.100.0.64 'base64 -w0 /etc/step-ca/secrets/intermediate_ca_key')"
      FINGERPRINT="$(timeout 20 ssh $SSH_OPTS root@10.100.0.64 'step certificate fingerprint /etc/step-ca/certs/root_ca.crt')"
      CA_JSON_B64="$(timeout 20 ssh $SSH_OPTS root@10.100.0.64 'base64 -w0 /etc/step-ca/config/ca.json')"

      timeout 20 op item edit "$ITEM_ID" \
        --vault="Kubernetes" \
        "hostname[text]=pki.sulibot.com" \
        "host_node[text]=pki01.sulibot.com" \
        "ca_url[text]=https://pki.sulibot.com" \
        "ca_password[password]=${var.smallstep_ca_password}" \
        "provisioner_password[password]=${var.smallstep_provisioner_password}" \
        "root_ca_crt[text]=$ROOT_CRT" \
        "intermediate_ca_crt[text]=$INTERMEDIATE_CRT" \
        "root_ca_fingerprint[text]=$FINGERPRINT" \
        "intermediate_ca_key_base64[concealed]=$INTERMEDIATE_KEY_B64" \
        "ca_json_base64[concealed]=$CA_JSON_B64" || {
          echo "Skipping 1Password PKI sync: update timed out or failed"
          exit 0
        }
    OPCMD
  }
}
