---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: default
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/part-of: cluster-104
spec:
  type: NodePort
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv6
    - IPv4
  selector:
    app.kubernetes.io/name: home-assistant
  ports:
    - name: http
      appProtocol: kubernetes.io/ws
      port: 8123
      targetPort: http
      nodePort: 30123
