---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tqm
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tqm-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          clients:
            qb:
              enabled: true
              type: qbittorrent
              url: http://qbittorrent.default.svc.cluster.local
              user: {{ .qbittorrent_username }}
              password: {{ .qbittorrent_password }}
              download_path: /media/Downloads/qbittorrent
              free_space_path: /media/Downloads/qbittorrent
              filter: default

          filters:
            default:
              ignore:
                - IsTrackerDown()
                - Downloaded == false
              remove:
                - IsUnregistered()
                - HasMissingFiles()
              tag:
                - name: low-seed
                  uploadKb: 100
                  update:
                    - Seeds <= 2 && IsPrivate == true
  data:
    - secretKey: qbittorrent_username
      remoteRef:
        key: qbittorrent
        property: username
    - secretKey: qbittorrent_password
      remoteRef:
        key: qbittorrent
        property: password
