---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tqm
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tqm-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          clients:
            qb:
              enabled: true
              type: qbittorrent
              url: http://qbittorrent.default.svc.cluster.local
              user: {{ .qbittorrent_username }}
              password: {{ .qbittorrent_password }}
  data:
    - secretKey: qbittorrent_username
      remoteRef:
        key: tqm
        property: username
    - secretKey: qbittorrent_password
      remoteRef:
        key: tqm
        property: password
