---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notifier
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: notifier-secret
    template:
      data:
        APPRISE_JELLYSEERR_PUSHOVER_URL: pover://{{ .PUSHOVER_USER_KEY }}@{{ .PUSHOVER_JELLYSEERR_TOKEN }}
        APPRISE_RADARR_PUSHOVER_URL: pover://{{ .PUSHOVER_USER_KEY }}@{{ .PUSHOVER_RADARR_TOKEN }}
        APPRISE_SONARR_PUSHOVER_URL: pover://{{ .PUSHOVER_USER_KEY }}@{{ .PUSHOVER_SONARR_TOKEN }}
  dataFrom:
    - extract:
        key: pushover
