---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notifiarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: notifiarr-secret
    template:
      data:
        DN_API_KEY: "{{ .NOTIFIARR_API_KEY }}"
        DN_RADARR_0_API_KEY: "{{ .radarr_RADARR_API_KEY }}"
        DN_RADARR_1_API_KEY: "{{ .radarr_4k_RADARR_API_KEY }}"
        DN_SONARR_0_API_KEY: "{{ .sonarr_SONARR_API_KEY }}"
        DN_SONARR_1_API_KEY: "{{ .sonarr_4k_SONARR_API_KEY }}"
  data:
    - secretKey: NOTIFIARR_API_KEY
      remoteRef:
        key: notifiarr
        property: NOTIFIARR_API_KEY
    - secretKey: radarr_RADARR_API_KEY
      remoteRef:
        key: radarr
        property: RADARR_API_KEY
    - secretKey: radarr_4k_RADARR_API_KEY
      remoteRef:
        key: radarr-4k
        property: RADARR_API_KEY
    - secretKey: sonarr_SONARR_API_KEY
      remoteRef:
        key: sonarr
        property: SONARR_API_KEY
    - secretKey: sonarr_4k_SONARR_API_KEY
      remoteRef:
        key: sonarr-4k
        property: SONARR_API_KEY
