---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: notifiarr
spec:
  chartRef:
    kind: OCIRepository
    name: notifiarr
  interval: 1h
  timeout: 10m
  maxHistory: 3
  install:
    remediation:
      retries: 5
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
      strategy: rollback
    timeout: 10m
  values:
    controllers:
      notifiarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/notifiarr/notifiarr
              tag: v0.9.5@sha256:a9a1f37f924d740107874675df6b6a5edd87e5f66ca72ad27481a4bdfd42d162
            env:
              TZ: America/Los_Angeles
              DN_UPSTREAMS_0: "[10.101.0.0/16,fd00:101::/48]"
              DN_RADARR_0_URL: http://radarr.default.svc.cluster.local
              DN_RADARR_1_URL: http://radarr-4k.default.svc.cluster.local
              DN_SONARR_0_URL: http://sonarr.default.svc.cluster.local
              DN_SONARR_1_URL: http://sonarr-4k.default.svc.cluster.local
              TMPDIR: /tmp
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      hostname: notifiarr
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ipFamilyPolicy: PreferDualStack
        ipFamilies: [IPv6, IPv4]
        ports:
          http:
            port: &port 5454
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.sulibot.com"
        parentRefs:
          - name: gateway-internal
            namespace: network
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: csi-cephfs-config-sc
        accessMode: ReadWriteMany
        size: 100Mi
      tmp:
        type: emptyDir
