apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: matter-server
  labels:
    app.kubernetes.io/name: matter-server
    app.kubernetes.io/part-of: cluster-104
spec:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv6
    - IPv4
  selector:
    app.kubernetes.io/name: matter-server
  ports:
    - name: http
      port: 5580
      targetPort: http
      protocol: TCP
