---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: user-storage
  namespace: flux-system
  labels:
    layer: "infrastructure"
    component: storage
    critical: "false"
spec:
  dependsOn:
    - name: storage-ready
      namespace: flux-system
  interval: 15m
  retryInterval: 30s
  path: ./kubernetes/apps/tier-1-infrastructure/user-storage/app
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
