---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: multi-scrobbler
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: multi-scrobbler-secret
    template:
      data:
        LISTENBRAINZ_TOKEN: "{{ .API_KEY }}"
        NAVIDROME_USERNAME: "{{ .username }}"
        NAVIDROME_PASSWORD: "{{ .password }}"
  data:
    - secretKey: API_KEY
      remoteRef:
        key: MusicBrainz
        property: API_KEY
    - secretKey: username
      remoteRef:
        key: Navidrome - sulibot
        property: username
    - secretKey: password
      remoteRef:
        key: Navidrome - sulibot
        property: password
