---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multi-scrobbler-config
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-cephfs-config-sc
  resources:
    requests:
      storage: 1Gi
