# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
locals {
  use_token = length(trimspace(var.pve_api_token_id)) > 0 && length(trimspace(var.pve_api_token_secret)) > 0
}
provider "proxmox" {
  endpoint  = var.pve_endpoint
  api_token = local.use_token ? "${var.pve_api_token_id}=${var.pve_api_token_secret}" : null
  username  = local.use_token ? null : var.pve_username
  password  = local.use_token ? null : var.pve_password
  insecure  = true # <-- was 'nsecure'; fixed

  # ---- SSH config used for uploading snippets/files to nodes ----
  ssh {
    username    = coalesce(var.pve_ssh_user, "root")
    agent       = var.pve_ssh_agent
    private_key = var.pve_ssh_private_key # leave null to rely on ssh-agent
    # NOTE: host is not supported here; use PROXMOX_SSH_HOST env var if needed
  }
}

provider "external" {}
provider "sops" {}
