---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller
  namespace: flux-system
  labels:
    layer: foundation
spec:
  dependsOn:
    - name: snapshot-controller-crds
      namespace: flux-system
  interval: 15m
  retryInterval: 30s
  path: ./kubernetes/apps/tier-0-foundation/snapshot-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-system
  wait: true
