---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelfmark
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: shelfmark-secret
    template:
      data:
        HARDCOVER_API_KEY: "{{ .HARDCOVER_API_KEY }}"
        PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
        OIDC_CLIENT_ID: '{{ index . "SHELFMARK_OIDC_CLIENT_ID" | default "shelfmark" }}'
        OIDC_CLIENT_SECRET: '{{ index . "SHELFMARK_OIDC_CLIENT_SECRET" | default "" }}'
        BOOTSTRAP_ADMIN_USERNAME: '{{ index . "username" | default "" }}'
        BOOTSTRAP_ADMIN_PASSWORD: '{{ index . "BOOTSTRAP_ADMIN_PASSWORD" | default "" }}'
  dataFrom:
    - extract:
        key: shelfmark
    - extract:
        key: shelfmark-bootstrap
    - extract:
        key: authentik
