#!/usr/bin/env bash
# Shows status of all clusters
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TERRAFORM_BASE="${REPO_ROOT}/terraform/infra/live"
TALOS_BASE="${REPO_ROOT}/talos/clusters"

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                    Cluster Status Overview                    ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Find all cluster directories
CLUSTERS=()
for cluster_dir in "${TERRAFORM_BASE}"/cluster-*; do
  if [[ -d "${cluster_dir}" ]]; then
    cluster_id=$(basename "${cluster_dir}" | sed 's/cluster-//')
    CLUSTERS+=("${cluster_id}")
  fi
done

if [[ ${#CLUSTERS[@]} -eq 0 ]]; then
  echo "No clusters found in ${TERRAFORM_BASE}"
  exit 0
fi

for cluster_id in "${CLUSTERS[@]}"; do
  terraform_dir="${TERRAFORM_BASE}/cluster-${cluster_id}"
  talos_dir="${TALOS_BASE}/cluster-${cluster_id}"

  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "📦 Cluster ${cluster_id}"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  # Read cluster configuration
  if [[ -f "${terraform_dir}/cluster.hcl" ]]; then
    cluster_name=$(grep -E '^\s*cluster_name\s*=' "${terraform_dir}/cluster.hcl" | sed -E 's/.*=\s*"([^"]+)".*/\1/' || echo "unknown")
    controlplanes=$(grep -E '^\s*controlplanes\s*=' "${terraform_dir}/cluster.hcl" | sed -E 's/.*=\s*([0-9]+).*/\1/' || echo "?")
    workers=$(grep -E '^\s*workers\s*=' "${terraform_dir}/cluster.hcl" | sed -E 's/.*=\s*([0-9]+).*/\1/' || echo "?")

    echo "  Name: ${cluster_name}"
    echo "  Topology: ${controlplanes} control planes, ${workers} workers"
  fi

  # Check Terraform state
  echo ""
  echo "  🏗️  Infrastructure:"

  if [[ -f "${terraform_dir}/image/.terraform.lock.hcl" ]]; then
    echo "    ✅ Image: Terraform initialized"
  else
    echo "    ⏸️  Image: Not initialized"
  fi

  if [[ -d "${terraform_dir}/nodes/.terragrunt-cache" ]]; then
    # Check if state exists in cache
    if find "${terraform_dir}/nodes/.terragrunt-cache" -name "terraform.tfstate" -type f | grep -q .; then
      echo "    ✅ Nodes: Deployed"

      # Try to get resource count
      state_file=$(find "${terraform_dir}/nodes/.terragrunt-cache" -name "terraform.tfstate" -type f | head -1)
      if [[ -f "${state_file}" ]]; then
        resource_count=$(grep -o '"type"' "${state_file}" 2>/dev/null | wc -l | tr -d ' ')
        if [[ "${resource_count}" -gt 0 ]]; then
          echo "      Resources: ${resource_count}"
        fi
      fi
    else
      echo "    ⏸️  Nodes: Not deployed"
    fi
  else
    echo "    ⏸️  Nodes: Not initialized"
  fi

  # Check Talos configurations
  echo ""
  echo "  ⚙️  Talos Configuration:"

  if [[ -d "${talos_dir}" ]]; then
    if [[ -f "${talos_dir}/talsecret.sops.yaml" ]]; then
      echo "    ✅ Secrets: Encrypted secrets present"
    else
      echo "    ⚠️  Secrets: Missing (run: task talos:gen-secrets -- ${cluster_id})"
    fi

    if [[ -f "${talos_dir}/talenv.yaml" ]]; then
      echo "    ✅ Environment: Generated by Terraform"
    else
      echo "    ⚠️  Environment: Missing (run: terragrunt apply in nodes/)"
    fi

    # Count machine configs
    config_count=$(find "${talos_dir}" -maxdepth 1 -name "cluster-${cluster_id}-*.yaml" -type f 2>/dev/null | wc -l | tr -d ' ')
    if [[ "${config_count}" -gt 0 ]]; then
      echo "    ✅ Machine Configs: ${config_count} files"
    else
      echo "    ⚠️  Machine Configs: Missing (run: task talos:gen-config -- ${cluster_id})"
    fi

    if [[ -f "${talos_dir}/talosconfig" ]]; then
      echo "    ✅ Talos CLI: Config present"
    else
      echo "    ⚠️  Talos CLI: Config missing"
    fi
  else
    echo "    ⏸️  Not configured"
  fi

  # Kubernetes cluster status (if talosconfig exists)
  if [[ -f "${talos_dir}/talosconfig" ]]; then
    echo ""
    echo "  ☸️  Kubernetes Cluster:"

    # Try to get cluster info
    if command -v talosctl &> /dev/null; then
      # Get first control plane IP from talenv.yaml
      if [[ -f "${talos_dir}/talenv.yaml" ]]; then
        cp_ip=$(grep -E 'cp0[0-9].*ipAddress' "${talos_dir}/talenv.yaml" | head -1 | awk '{print $2}' || echo "")

        if [[ -n "${cp_ip}" ]]; then
          if talosctl --talosconfig "${talos_dir}/talosconfig" --nodes "${cp_ip}" version --short 2>/dev/null | grep -q "Server"; then
            echo "    ✅ Cluster: Reachable"

            # Try to get node count
            if command -v kubectl &> /dev/null && [[ -f "${talos_dir}/kubeconfig" ]]; then
              export KUBECONFIG="${talos_dir}/kubeconfig"
              node_count=$(kubectl get nodes --no-headers 2>/dev/null | wc -l | tr -d ' ')
              ready_count=$(kubectl get nodes --no-headers 2>/dev/null | grep -c " Ready " || echo "0")

              if [[ "${node_count}" -gt 0 ]]; then
                echo "      Nodes: ${ready_count}/${node_count} ready"
              fi
            fi
          else
            echo "    ⚠️  Cluster: Not reachable"
          fi
        fi
      fi
    fi
  fi

  echo ""
done

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Run './scripts/validate-cluster.sh <cluster_id>' for detailed validation"
echo ""
