#!/usr/bin/env bash
# Validates cluster configuration consistency
set -euo pipefail

CLUSTER_ID="${1:-}"
if [[ -z "${CLUSTER_ID}" ]]; then
  echo "Usage: $0 <cluster_id>"
  echo "Example: $0 101"
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TERRAFORM_DIR="${REPO_ROOT}/terraform/infra/live/cluster-${CLUSTER_ID}"
TALOS_DIR="${REPO_ROOT}/talos/clusters/cluster-${CLUSTER_ID}"

echo "🔍 Validating cluster-${CLUSTER_ID}..."
echo ""

ERRORS=0
WARNINGS=0

# Check directories exist
if [[ ! -d "${TERRAFORM_DIR}" ]]; then
  echo "❌ Terraform cluster directory missing: ${TERRAFORM_DIR}"
  ERRORS=$((ERRORS + 1))
fi

if [[ ! -d "${TALOS_DIR}" ]]; then
  echo "⚠️  Talos cluster directory missing: ${TALOS_DIR}"
  echo "   (This is OK if cluster not yet bootstrapped)"
  WARNINGS=$((WARNINGS + 1))
fi

# Check cluster.hcl consistency
if [[ -f "${TERRAFORM_DIR}/cluster.hcl" ]]; then
  CLUSTER_NAME=$(grep -E '^\s*cluster_name\s*=' "${TERRAFORM_DIR}/cluster.hcl" | sed -E 's/.*=\s*"([^"]+)".*/\1/')
  CLUSTER_ID_HCL=$(grep -E '^\s*cluster_id\s*=' "${TERRAFORM_DIR}/cluster.hcl" | sed -E 's/.*=\s*([0-9]+).*/\1/')

  if [[ "${CLUSTER_NAME}" != "${CLUSTER_ID}" ]]; then
    echo "⚠️  cluster_name (${CLUSTER_NAME}) should match directory name (${CLUSTER_ID})"
    WARNINGS=$((WARNINGS + 1))
  fi

  if [[ "${CLUSTER_ID_HCL}" != "${CLUSTER_ID}" ]]; then
    echo "❌ cluster_id in .hcl (${CLUSTER_ID_HCL}) doesn't match expected (${CLUSTER_ID})"
    ERRORS=$((ERRORS + 1))
  fi

  echo "✅ cluster.hcl: cluster_name=${CLUSTER_NAME}, cluster_id=${CLUSTER_ID_HCL}"
else
  echo "❌ cluster.hcl not found in ${TERRAFORM_DIR}"
  ERRORS=$((ERRORS + 1))
fi

# Check for required files
echo ""
echo "📄 Checking required files..."

if [[ -f "${TERRAFORM_DIR}/image/terragrunt.hcl" ]]; then
  echo "✅ image/terragrunt.hcl exists"
else
  echo "❌ image/terragrunt.hcl missing"
  ERRORS=$((ERRORS + 1))
fi

if [[ -f "${TERRAFORM_DIR}/nodes/terragrunt.hcl" ]]; then
  echo "✅ nodes/terragrunt.hcl exists"
else
  echo "❌ nodes/terragrunt.hcl missing"
  ERRORS=$((ERRORS + 1))
fi

# Check Talos files (if directory exists)
if [[ -d "${TALOS_DIR}" ]]; then
  echo ""
  echo "📄 Checking Talos files..."

  if [[ -f "${TALOS_DIR}/talsecret.sops.yaml" ]]; then
    echo "✅ talsecret.sops.yaml exists"
  else
    echo "⚠️  talsecret.sops.yaml missing (run: task talos:gen-secrets -- ${CLUSTER_ID})"
    WARNINGS=$((WARNINGS + 1))
  fi

  if [[ -f "${TALOS_DIR}/talenv.yaml" ]]; then
    echo "✅ talenv.yaml exists"
  else
    echo "⚠️  talenv.yaml missing (generated by: terragrunt apply)"
    WARNINGS=$((WARNINGS + 1))
  fi

  # Count machine configs
  CONFIG_COUNT=$(find "${TALOS_DIR}" -maxdepth 1 -name "cluster-${CLUSTER_ID}-*.yaml" -type f 2>/dev/null | wc -l | tr -d ' ')
  if [[ "${CONFIG_COUNT}" -gt 0 ]]; then
    echo "✅ ${CONFIG_COUNT} machine configs found"
  else
    echo "⚠️  No machine configs found (run: task talos:gen-config -- ${CLUSTER_ID})"
    WARNINGS=$((WARNINGS + 1))
  fi
fi

# Summary
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [[ "${ERRORS}" -eq 0 ]] && [[ "${WARNINGS}" -eq 0 ]]; then
  echo "✅ Validation passed with no errors or warnings"
  exit 0
elif [[ "${ERRORS}" -eq 0 ]]; then
  echo "⚠️  Validation passed with ${WARNINGS} warning(s)"
  exit 0
else
  echo "❌ Validation failed with ${ERRORS} error(s) and ${WARNINGS} warning(s)"
  exit 1
fi
