---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: atuin-secret
    creationPolicy: Owner
    template:
      data:
        ATUIN_DB_URI: "postgres://atuin:{{ .ATUIN_DB_PASSWORD }}@postgres-vectorchord-rw.default.svc.cluster.local:5432/atuin?sslmode=disable"
  dataFrom:
    - extract:
        key: atuin
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: atuin-pg-password
    creationPolicy: Owner
    template:
      data:
        username: atuin
        password: "{{ .ATUIN_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: atuin
