---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-vectorchord
  namespace: default
  labels:
    app.kubernetes.io/name: postgres-vectorchord
    app.kubernetes.io/part-of: postgres-vectorchord
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      cnpg.io/cluster: postgres-vectorchord
      cnpg.io/podRole: instance
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
