---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: keda-admission-webhooks
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keda-admission-webhooks
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsOnly
        minAllowed:
          cpu: 10m
          memory: 64Mi
        maxAllowed:
          cpu: "4"
          memory: 16Gi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: keda-operator
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keda-operator
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsOnly
        minAllowed:
          cpu: 10m
          memory: 64Mi
        maxAllowed:
          cpu: "4"
          memory: 16Gi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: keda-operator-metrics-apiserver
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keda-operator-metrics-apiserver
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsOnly
        minAllowed:
          cpu: 10m
          memory: 64Mi
        maxAllowed:
          cpu: "4"
          memory: 16Gi
