---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twenty
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: twenty-secret
    creationPolicy: Owner
    template:
      data:
        PG_DATABASE_URL: 'postgres://twenty:{{ .TWENTY_DB_PASSWORD }}@postgres-vectorchord-rw.default.svc.cluster.local:5432/twenty'
        REDIS_URL: 'redis://:{{ .VALKEY_PASSWORD }}@127.0.0.1:6379'
        APP_SECRET: '{{ .TWENTY_APP_SECRET }}'
  dataFrom:
    - extract:
        key: twenty
    - extract:
        key: valkey
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twenty-pg
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: twenty-pg-password
    creationPolicy: Owner
    template:
      data:
        username: twenty
        password: '{{ .TWENTY_DB_PASSWORD }}'
  dataFrom:
    - extract:
        key: twenty
