---
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: twenty
spec:
  target:
    service: twenty
    port: 3000
  rules:
    - hosts:
        - twenty.sulibot.com
  scalingMetric:
    concurrency:
      targetValue: 10
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: twenty-server-http
spec:
  scaleTargetRef:
    name: twenty-server
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 1800
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.observability:9090
        interceptorRoute: twenty
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: twenty-worker-http
spec:
  scaleTargetRef:
    name: twenty-worker
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 1800
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.observability:9090
        interceptorRoute: twenty
