apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- canary.yaml
- cluster-settings.yaml
- gotk-components.yaml
- gotk-sync.yaml
patches:
- path: ../../../flux/flux-system/patches/kustomize-controller-concurrency.yaml
  target:
    kind: Deployment
    name: kustomize-controller
- path: ../../../flux/flux-system/patches/helm-controller-concurrency.yaml
  target:
    kind: Deployment
    name: helm-controller
- path: ../../../flux/flux-system/patches/source-controller-concurrency.yaml
  target:
    kind: Deployment
    name: source-controller
