---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprints
data:
  google-source.yaml: |
    version: 1
    metadata:
      name: Google OAuth Source
      labels:
        blueprints.goauthentik.io/instantiate: "true"
    entries:
      - model: authentik_sources_oauth.oauthsource
        state: present
        identifiers:
          slug: google
        attrs:
          name: Google
          slug: google
          enabled: true
          authentication_flow: !Find [authentik_flows.flow, [slug, default-source-authentication]]
          enrollment_flow: !Find [authentik_flows.flow, [slug, default-source-enrollment]]
          provider_type: google
          consumer_key: !Env GOOGLE_CLIENT_ID
          consumer_secret: !Env GOOGLE_CLIENT_SECRET
          additional_scopes: "email profile"
          user_matching_mode: identifier
          user_path_template: "goauthentik.io/sources/%(slug)s"
