---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authentik
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: authentik
    namespace: default
  install:
    remediation:
      retries: 5
    timeout: 30m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
    timeout: 30m
  maxHistory: 3
  values:
    global:
      podAnnotations:
        reloader.stakater.com/auto: "true"
      deploymentStrategy:
        type: Recreate
      envFrom:
        - secretRef:
            name: authentik-secret
    authentik:
      log_level: info
      postgresql:
        port: 5432
        name: ""
        user: ""
        password: ""
      redis:
        host: ""
        password: ""
    postgresql:
      enabled: false
    redis:
      enabled: true
      master:
        persistence:
          enabled: false
    prometheus:
      rules:
        enabled: true
    blueprints:
      configMaps:
        - authentik-blueprints
    server:
      replicas: 1
      startupProbe:
        failureThreshold: 180
        tcpSocket:
          port: http
        periodSeconds: 10
        timeoutSeconds: 5
      ingress:
        enabled: false
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    worker:
      replicas: 1
      livenessProbe:
        tcpSocket:
          port: http
      readinessProbe:
        tcpSocket:
          port: http
      startupProbe:
        failureThreshold: 180
        tcpSocket:
          port: http
        periodSeconds: 10
        timeoutSeconds: 5
