---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nzbget
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nzbget-secret
    template:
      data:
        NZBGET__CONTROLUSERNAME: "{{ .username }}"
        NZBGET__CONTROLPASSWORD: "{{ .password }}"
        NZBGET__FRUGAL_USERNAME: '{{ .NZBGET__FRUGAL_USERNAME | default "" }}'
        NZBGET__FRUGAL_PASSWORD: '{{ .NZBGET__FRUGAL_PASSWORD | default "" }}'
        NZBGET__BLOCKNEWS_USERNAME: '{{ .NZBGET__BLOCKNEWS_USERNAME | default "" }}'
        NZBGET__BLOCKNEWS_PASSWORD: '{{ .NZBGET__BLOCKNEWS_PASSWORD | default "" }}'
  dataFrom:
    - extract:
        key: nzbget
  data:
    - secretKey: NZBGET__FRUGAL_USERNAME
      remoteRef:
        key: frugal
        property: email
    - secretKey: NZBGET__FRUGAL_PASSWORD
      remoteRef:
        key: frugal
        property: pass
    - secretKey: NZBGET__BLOCKNEWS_USERNAME
      remoteRef:
        key: blocknews
        property: username
    - secretKey: NZBGET__BLOCKNEWS_PASSWORD
      remoteRef:
        key: blocknews
        property: password
