---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mediasage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mediasage-secret
    template:
      data:
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
  data:
    - secretKey: PLEX_TOKEN
      remoteRef:
        key: plex
        property: PLEX_TOKEN
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: search-ops
        property: OPENAI_API_KEY
