apiVersion: v1
kind: Secret
metadata:
    name: synch-secret
    namespace: default
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:dFcehHzC4/WCchWIETVzRMIr+L2e+8hZf/xNdhuxpMFUeksfN0s+Z+xVlCn9mIP+T/A2OasVrqoOcjtZ7iIyhA==,iv:sht7xawVs/e9fdOzE4SHVEPzioOQsN8Hxx6RTLdGyaQ=,tag:EJJ4LtjZsrBx1nrSnccm5w==,type:str]
    SYNC_TOKEN_SECRET: ENC[AES256_GCM,data:ie2pfrJfUCV3V/kHkv8LKxeHOzRtlT+NhWcpd7sHLZwccQZv+LVz2+ZrJuCp9IYsmawqWV+bnQiKyxwH2hrg/A==,iv:BLnfhzZpEIf9g3oEOhcCOHejT7pcR62dhyOJSCNMvEQ=,tag:SUkIt6MwKhLJ+8WeQHYaDw==,type:str]
sops:
    age:
        - recipient: age1k3sunyva3kc3jusxs3j93nyueqjgzcgg6s6qghn8aeqpuy7l35wss8gxvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMlJ3NEZOQ216QzR3cmlX
            ay80aU5nZDN2OUxLUDJ3Y25rM3Fsd0N5REhNCmlGZVh1dU1NS3pBeDJ4cmRTcmdl
            RStoSkFSaUVvbXowdnA2T3E3NnB3SjAKLS0tIHJhUUVkd2k0TEhGMWY1YlhMa3hM
            S0VZOFVSVDdmVnM2QW8yWXpNS3kvaEkKWKIyL9jOpFD3ChALLDX704UE6N3LMzRf
            wpdwaL+PsJ021qnA1rDDnGca4ftmAgUt26Yc3SwZY0H95JAu9p6Nug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T16:27:00Z"
    mac: ENC[AES256_GCM,data:XamLRPbT9mJ6RiXlsL0ExWLQLZ6p3ZgEbxfJsz9TTx3Ge8tK2RqJpKpYEePnpbIFij70r8foHtDVem+ZFgcaJeiB/D2eS82OWXktdPSxhRiNQ4/R1sNwZG1+PXDMT7IaGiObX5y89fx08SmBT9MmcYH7bC0FSaAyzvIDfRzWE9Q=,iv:mxqOQVJDw/+2TZCKJchKc3TwGTEiRSXkL+GmlL6ErVs=,tag:ZM4mdW9zugNjarYD1TCdYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
