---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-config
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: csi-cephfs-config-sc
