---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./owner-bootstrap-externalsecret.yaml
  - ./owner-bootstrap-job.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./vpa.yaml
