---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
data:
  config.yaml: |
    server:
      database: /config/database.db
      sources:
        - path: /data
          name: Data
    auth:
      methods:
        password:
          enabled: true
        proxy:
          enabled: true
          header: "X-authentik-email"
          createUser: true
