---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: filebrowser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: filebrowser-secret
    creationPolicy: Owner
    template:
      data:
        # Set these fields in 1Password item `filebrowser`:
        # - FILEBROWSER_ADMIN_EMAIL (ex: admin@sulibot.com)
        # - FILEBROWSER_ADMIN_PASSWORD
        FB_USERNAME: "{{ .FILEBROWSER_ADMIN_EMAIL }}"
        FB_PASSWORD: "{{ .FILEBROWSER_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: filebrowser
