---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    template:
      data:
        HOMEPAGE_VAR_PLEX_TOKEN: "{{ .plex_PLEX_TOKEN }}"
        HOMEPAGE_VAR_SONARR_API_KEY: "{{ .sonarr_SONARR_API_KEY }}"
        HOMEPAGE_VAR_SONARR_4K_API_KEY: "{{ .sonarr_4k_SONARR_API_KEY }}"
        HOMEPAGE_VAR_RADARR_API_KEY: "{{ .radarr_RADARR_API_KEY }}"
        HOMEPAGE_VAR_RADARR_4K_API_KEY: "{{ .radarr_4k_RADARR_API_KEY }}"
        HOMEPAGE_VAR_LIDARR_API_KEY: "{{ .lidarr_LIDARR_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_API_KEY: "{{ .prowlarr_PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_SEERR_API_KEY: "{{ .seerr_SEERR_API_KEY }}"
        HOMEPAGE_VAR_NZBGET_USER: "{{ .nzbget_NZBGET_USER }}"
        HOMEPAGE_VAR_NZBGET_PASS: "{{ .nzbget_NZBGET_PASS }}"
        HOMEPAGE_VAR_IMMICH_API_KEY: "{{ .immich_IMMICH_API_KEY }}"
  dataFrom:
    - extract:
        key: plex
      rewrite:
        - regexp:
            source: "(.*)"
            target: "plex_$1"
    - extract:
        key: sonarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sonarr_$1"
    - extract:
        key: sonarr-4k
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sonarr_4k_$1"
    - extract:
        key: radarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "radarr_$1"
    - extract:
        key: radarr-4k
      rewrite:
        - regexp:
            source: "(.*)"
            target: "radarr_4k_$1"
    - extract:
        key: lidarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "lidarr_$1"
    - extract:
        key: prowlarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "prowlarr_$1"
    - extract:
        key: seerr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "seerr_$1"
    - extract:
        key: nzbget
      rewrite:
        - regexp:
            source: "(.*)"
            target: "nzbget_$1"
    - extract:
        key: immich
      rewrite:
        - regexp:
            source: "(.*)"
            target: "immich_$1"
