---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/kopiamaintenance_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: daily
  namespace: volsync-system
spec:
  enabled: true
  schedule: 0 */6 * * *
  trigger:
    schedule: 30 */6 * * *
  repository:
    repository: volsync-maintenance-secret
