# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {}

  required_providers {
    proxmox = { source = "bpg/proxmox", version = "~> 0.96.0" }
    sops    = { source = "carlpett/sops", version = "~> 1.3.0" }
  }
}

variable "region" {
  type    = string
  default = "home-lab"
}

# RouterOS CHR test VM — VLAN 200 (same network as zot VM at 10.200.0.51)
#
# Pre-requisite: upload chr-7.17.2.qcow2 to resources:import/
#   ssh root@10.10.0.1
#   IMPORT_DIR=$(pvesm path resources:import/debian-trixie-cloud-amd64.qcow2 | xargs dirname)
#   wget https://download.mikrotik.com/routeros/7.17.2/chr-7.17.2.img.zip
#   unzip chr-7.17.2.img.zip
#   qemu-img convert -f raw -O qcow2 chr-7.17.2.img chr-7.17.2.qcow2
#   mv chr-7.17.2.qcow2 $$IMPORT_DIR/
#
# First-boot setup (Proxmox console):
#   /ip/address/add address=10.200.0.250/24 interface=ether1
#   /ip/route/add gateway=10.200.0.254
#   /user/set admin password=<routeros_test_password from secrets.sops.yaml>
#   /ip/service/set [find name=www-ssl] disabled=no
resource "proxmox_virtual_environment_vm" "routeros_chr" {
  vm_id           = 9900
  name            = "routeros-chr-test"
  node_name       = "pve01"
  started         = true
  stop_on_destroy = true
  on_boot         = false

  cpu {
    cores = 1
    type  = "x86-64-v2-AES"
  }

  memory {
    dedicated = 512
  }

  disk {
    datastore_id = "rbd-vm"
    file_id      = "resources:import/chr-7.17.2.qcow2"
    interface    = "virtio0"
    size         = 1
  }

  network_device {
    bridge  = "vmbr0"
    vlan_id = 200
    model   = "virtio"
  }

  boot_order = ["virtio0"]

  vga {
    type = "std"
  }
}

output "chr_vm_id" {
  value = proxmox_virtual_environment_vm.routeros_chr.vm_id
}

output "chr_instructions" {
  value = "First-boot: open Proxmox console, set IP 10.200.0.250/24, gateway 10.200.0.254, admin password, enable www-ssl service"
}
