# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "sops" {}

data "sops_file" "proxmox" {
  source_file = "/Users/sulibot/repos/github/home-ops/terraform/infra/live/common/secrets.sops.yaml"
}

provider "proxmox" {
  endpoint = data.sops_file.proxmox.data["pve_endpoint"]
  username = "root@pam"
  password = data.sops_file.proxmox.data["pve_password"]
  insecure = true

  ssh {
    agent       = false
    username    = "root"
    private_key = file(pathexpand("~/.ssh/id_ed25519"))
  }
}
