[all:vars]
ansible_user=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3

[jool]
jool ansible_host=fd00:200::64 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ed25519

[tayga]
tayga01 ansible_host=10.0.200.64 ansible_service_host=fd00:200::64 node_role=utility
